PX 915 Project Title/Name Here: Biased_Optim_example_driver.f90 File Reference
Biased_Optim_example_driver.f90 File Reference
Modules
module log_rho_mod
Functions/Subroutines
real(dp) function log_rho_mod::log_rho (x, dof)
program main
Function/Subroutine Documentation
main()
program main
Definition at line 21 of file Biased_Optim_example_driver.f90.
References param_search::best_params, param_search::best_trial, biased_optim::bi_op_step(), basis_functions::deinitialise_basis(), basis_functions::dof_bounds, shared_constants::dp, shared_constants::electronvolt, param_search::find_best_params(), gp_surrogate::gp_debug_print_state(), gp_surrogate::gp_exit(), gp_surrogate::gp_min_stored(), basis_functions::initialise_basis(), param_search::latin_hypercube(), log_rho_mod::log_rho(), mcmc::mcmc_adapt(), mcmc::mcmc_sample(), basis_functions::number_dofs, param_search::param_wall_check(), basis_functions::reduced_hamiltonian, and stoch_grad::stoch_grad_exit().