PX 915: Variational Quantum Monte Carlo - LATIN: bond_driver.f90 File Reference
bond_driver.f90 File Reference
Driver for running multiple simulations to optimise bond length.
Functions/Subroutines
program bond_length_driver
Driver for running multiple simulations to optimise bondlength.
Detailed Description
Driver for running multiple simulations to optimise bond length.
Definition in file bond_driver.f90.
Function/Subroutine Documentation
bond_length_driver()
program bond_length_driver
Driver for running multiple simulations to optimise bondlength.
This code computes the ground state energy and corresponding trial wavefunction for a given atom and electron configuration. It saves the resulting wavefunction or electron density in netcdf.
Definition at line 7 of file bond_driver.f90.
References param_search::best_trial, basis_functions::deinitialise_basis(), basis_functions::dof_bounds, shared_constants::dp, param_search::find_best_params(), basis_functions::initialise_basis(), param_search::latin_hypercube(), basis_functions::log_density(), mcmc::mcmc_adapt(), mcmc::mcmc_sample(), basis_functions::n_space_dims, basis_functions::number_dofs, param_search::param_wall_check(), read_data::readtxt(), basis_functions::reduced_hamiltonian, and shared_constants::slater_1s_code.