PX 915 Project Title/Name Here: ed_test.f90 File Reference
ed_test.f90 File Reference
Functions/Subroutines
program main_driver
Function/Subroutine Documentation
main_driver()
program main_driver
Definition at line 1 of file ed_test.f90.
References basis_functions::deinitialise_basis(), electron_density_functions::electron_density(), and basis_functions::initialise_basis().