PX 915: Variational Quantum Monte Carlo - LATIN: GP_surrogate_test_driver.f90 File Reference
GP_surrogate_test_driver.f90 File Reference
Driver for testing the Gaussian process surrogate.
Functions/Subroutines
program main
Driver for testing the Gaussain process surrogate.
Detailed Description
Driver for testing the Gaussian process surrogate.
Definition in file GP_surrogate_test_driver.f90.
Function/Subroutine Documentation
main()
program main
Driver for testing the Gaussain process surrogate.
Definition at line 3 of file GP_surrogate_test_driver.f90.
References gp_surrogate::gp_mu_post(), gp_surrogate::gp_mu_post_grad(), gp_surrogate::gp_post_k_grad(), gp_surrogate::gp_update(), priors::prior_mean(), and priors::prior_mean_dx().