PX 915 Project Title/Name Here: latin_driver.f90 File Reference
latin_driver.f90 File Reference
desc soon
Functions/Subroutines
program main_driver
Main driver for simulation using the latin_hypercube search.
Detailed Description
desc soon
Definition in file latin_driver.f90.
Function/Subroutine Documentation
main_driver()
program main_driver
Main driver for simulation using the latin_hypercube search.
This code computes the ground state energy and corresponding trial wavefunction for a given atom and electron configuration. It saves the resulting wavefunction or electron density in netcdf.
Definition at line 7 of file latin_driver.f90.
References param_search::best_params, param_search::best_trial, calculations::calc(), basis_functions::deinitialise_basis(), basis_functions::dof_bounds, shared_constants::dp, shared_constants::electronvolt, param_search::find_best_params(), basis_functions::initialise_basis(), param_search::latin_hypercube(), basis_functions::log_density(), mcmc::mcmc_adapt(), mcmc::mcmc_sample(), basis_functions::n_space_dims, basis_functions::number_dofs, param_search::param_wall_check(), read_data::readtxt(), basis_functions::reduced_hamiltonian, write_file::result_netcdf(), shared_constants::slater_1s_code, and write_file::xy_grid().