PX 915 Project Title/Name Here: loop_test_update.f90 File Reference
loop_test_update.f90 File Reference
desc soon
Modules
module log_rho_mod
Functions/Subroutines
real(dp) function log_rho_mod::log_rho (x, dof)
program loop_test
Detailed Description
desc soon
Definition in file loop_test_update.f90.
Function/Subroutine Documentation
loop_test()
program loop_test
Definition at line 21 of file loop_test_update.f90.
References write_file::atom1_netcdf(), param_search::best_params, param_search::best_trial, basis_functions::deinitialise_basis(), basis_functions::dof_bounds, param_search::find_best_params(), basis_functions::initialise_basis(), param_search::latin_hypercube(), log_rho_mod::log_rho(), mcmc::mcmc_adapt(), mcmc::mcmc_sample(), param_search::param_wall_check(), basis_functions::reduced_hamiltonian, write_file::xyz_coords1d(), write_file::xyz_coords2d(), and write_file::xyz_coords3d().