PX 915 Project Title/Name Here: loop_test.f90 File Reference
loop_test.f90 File Reference
Modules
module log_rho_mod
Functions/Subroutines
real(dp) function log_rho_mod::log_rho (x, dof)
program loop_test
Function/Subroutine Documentation
loop_test()
program loop_test
Definition at line 21 of file loop_test.f90.
References param_search::best_params, param_search::best_trial, write_file::create_netcdf(), basis_functions::deinitialise_basis(), basis_functions::dof_bounds, param_search::find_best_params(), calculations::hamiltonian(), basis_functions::initialise_basis(), param_search::latin_hypercube(), log_rho_mod::log_rho(), mcmc::mcmc_adapt(), mcmc::mcmc_sample(), param_search::param_wall_check(), basis_functions::reduced_hamiltonian, calculations::wavefunction(), and write_file::xyz_coords().