PX 915 Project Title/Name Here: main_driver.f90 File Reference
main_driver.f90 File Reference
Functions/Subroutines
program main_driver
Main driver for simulation.
Function/Subroutine Documentation
main_driver()
program main_driver
Main driver for simulation.
More description to be added
Parameters
n_electrons_in Number of electrons
Definition at line 6 of file main_driver.f90.
References param_search::best_params, param_search::best_trial, biased_optim::bi_op_step(), basis_functions::deinitialise_basis(), basis_functions::dof_bounds, param_search::find_best_params(), basis_functions::initialise_basis(), param_search::latin_hypercube(), basis_functions::log_density(), mcmc::mcmc_adapt(), mcmc::mcmc_sample(), basis_functions::n_space_dims, basis_functions::number_dofs, param_search::param_wall_check(), read_data::readtxt(), and basis_functions::reduced_hamiltonian.