PX 915 Project Title/Name Here: MCMC_test_driver.f90 File Reference
MCMC_test_driver.f90 File Reference
Modules
module log_rho_mod
Functions/Subroutines
real(dp) function log_rho_mod::log_rho (x, dof)
program main
Function/Subroutine Documentation
main()
program main
Definition at line 21 of file MCMC_test_driver.f90.
References log_rho_mod::log_rho(), mcmc::mcmc_adapt(), and mcmc::mcmc_sample().