PX 915 Project Title/Name Here: electron_density_functions Module Reference
electron_density_functions Module Reference
Electron density function.
Functions/Subroutines
real(dp) function electron_density (fixed_position, integral_bounds, dof_coefficients, n_MC_points, seed_in)
Computes electron density for 2 electron simulations Uses basic Monte Carlo Integration.
real(dp) function wave_function_normalisation (integral_bounds, dof_coefficients, n_MC_points, seed_in)
Computes the integral of the wavefunction squared To normalise the wavefunction for outputing Uses basic Monte Carlo Integration.
Detailed Description
Electron density function.
Function/Subroutine Documentation
electron_density()
real(dp) function electron_density_functions::electron_density (real(dp), dimension(3), intent(in) fixed_position, real(dp), dimension(3,2), intent(in) integral_bounds, real(dp), dimension(:), intent(in) dof_coefficients, integer, intent(in) n_MC_points, integer, intent(in), optional seed_in)
Computes electron density for 2 electron simulations Uses basic Monte Carlo Integration.
Parameters
[in] fixed_position Space position of density
[in] integral_bounds bounds of integration box
[in] dof_coefficients Current dof parameters
[in] n_mc_points Number of Monte Carlo Points
[in] seed_in input seed
Definition at line 11 of file electron_density.f90.
     real(dp) :: electron_density
     real(dp), dimension(3), intent(in) :: fixed_position
     real(dp), dimension(3,2), intent(in) :: integral_bounds
     real(dp), dimension(:), intent(in) :: dof_coefficients
     integer, intent(in) :: n_MC_points
     integer, intent(in),optional :: seed_in
     integer, allocatable :: seed(:)
     integer :: i ! loop variables
     integer :: n
     real(dp) :: x,y,z,Lx,Ly,Lz
     real(dp), dimension(6) :: position_total
     if (present(seed_in)) then
       call random_seed(size=n)
       allocate(seed(n))
       seed = seed_in
       call random_seed(put=seed)
     end if
     do i=1,3
     if ((integral_bounds(i,2)-integral_bounds(i,1))<= 0.1) then
       print*, "Error, box too small or bounds incorrect"
     end if
     end do
     position_total(1:3) = 0.0_dp
     position_total(4:6) = fixed_position
     lx = integral_bounds(1,2)-integral_bounds(1,1)
     ly = integral_bounds(2,2)-integral_bounds(2,1)
     lz = integral_bounds(3,2)-integral_bounds(3,1)
     !$OMP parallel do default(shared) private(i,x,y,z) firstprivate(position_total) reduction(+:electron_density)
     do i=1,n_mc_points
       call random_number(x)
       call random_number(y)
       call random_number(z)
       x = lx*x +integral_bounds(1,1)
       y = ly*y +integral_bounds(2,1)
       z = lz*z +integral_bounds(3,1)
       position_total(4:6) = [x,y,z]
       electron_density = electron_density+wave_function(position_total,dof_coefficients)**2
     end do
     electron_density = 2*lx*ly*lz*electron_density/n_mc_points
     if (allocated(seed)) deallocate(seed)
References basis_functions::wave_function.
Referenced by calculations::calc(), and main_driver().
wave_function_normalisation()
real(dp) function electron_density_functions::wave_function_normalisation (real(dp), dimension(3,2), intent(in) integral_bounds, real(dp), dimension(:), intent(in) dof_coefficients, integer, intent(in) n_MC_points, integer, intent(in), optional seed_in)
Computes the integral of the wavefunction squared To normalise the wavefunction for outputing Uses basic Monte Carlo Integration.
Parameters
[in] integral_bounds bounds of integration box
[in] dof_coefficients Current dof parameters
[in] n_mc_points Number of Monte Carlo Points
[in] seed_in input seed
Definition at line 63 of file electron_density.f90.
     real(dp) :: wave_function_normalisation
     real(dp), dimension(3,2), intent(in) :: integral_bounds
     real(dp), dimension(:), intent(in) :: dof_coefficients
     integer, intent(in) :: n_MC_points
     integer, intent(in),optional :: seed_in
     integer, allocatable :: seed(:)
     integer :: i ! loop variables
     integer :: n
     real(dp) :: x,y,z,Lx,Ly,Lz
     real(dp), dimension(:),allocatable :: position_total
     if (present(seed_in)) then
       call random_seed(size=n)
       allocate(seed(n))
       seed = seed_in
       call random_seed(put=seed)
     end if
     do i=1,3
     if ((integral_bounds(i,2)-integral_bounds(i,1))<= 0.1) then
       print*, "Error, box too small or bounds incorrect"
     end if
     end do
     allocate(position_total(n_space_dims))
     lx = integral_bounds(1,2)-integral_bounds(1,1)
     ly = integral_bounds(2,2)-integral_bounds(2,1)
     lz = integral_bounds(3,2)-integral_bounds(3,1)
     !$OMP parallel do default(shared) private(i,x,y,z) firstprivate(position_total) reduction(+:wave_function_normalisation)
     do i=1,n_mc_points
       call random_number(x)
       call random_number(y)
       call random_number(z)
       x = lx*x +integral_bounds(1,1)
       y = ly*y +integral_bounds(2,1)
       z = lz*z +integral_bounds(3,1)
       position_total(1:3) = [x,y,z]
       if (n_space_dims == 6) then
         call random_number(x)
         call random_number(y)
         call random_number(z)
         x = lx*x +integral_bounds(1,1)
         y = ly*y +integral_bounds(2,1)
         z = lz*z +integral_bounds(3,1)
         position_total(4:6) = [x,y,z]
       end if
       wave_function_normalisation = wave_function_normalisation&
         +wave_function(position_total,dof_coefficients)**2
     end do
     wave_function_normalisation = lx*ly*lz*wave_function_normalisation/n_mc_points
     if (n_space_dims == 6) then
       wave_function_normalisation = lx*ly*lz*wave_function_normalisation
     end if
     if (allocated(seed)) deallocate(seed)
     deallocate(position_total)
References basis_functions::n_space_dims, and basis_functions::wave_function.
Referenced by calculations::calc().