PX 915 Project Title/Name Here: calculations Module Reference
calculations Module Reference
Function completing calculations of either the wavefunction or electron density (depending on the system) at a set of coordinates [x,y,0] on a grid of equally spaced points on a xy grid.
Functions/Subroutines
real(dp) function, dimension(:), allocatable calc (dof, points, box, n_ele, n_MCMC_steps)
calc function returns the wavefunction or electron density evaluated on a 2D xy plane (taking a slice) depending on the number of electrons in the system.
Detailed Description
Function completing calculations of either the wavefunction or electron density (depending on the system) at a set of coordinates [x,y,0] on a grid of equally spaced points on a xy grid.
Function/Subroutine Documentation
calc()
real(dp) function, dimension(:), allocatable calculations::calc (real(dp), dimension(:), intent(in) dof, integer, intent(in) points, real(dp), intent(in) box, integer, intent(in) n_ele, integer, intent(in) n_MCMC_steps)
calc function returns the wavefunction or electron density evaluated on a 2D xy plane (taking a slice) depending on the number of electrons in the system.
Sets the z coordinate to 0 as only evaluating on a xy plane.
Parameters
[in] points points is the user defined number of evaluation points for the plotting grid.
n_ele is the number of electrons in the system
n_MCMC_steps is the number of steps needed for the MCMC used for evaluating the electron density for the 2 electron case.
[in] n_ele points is the user defined number of evaluation points for the plotting grid.
n_ele is the number of electrons in the system
n_MCMC_steps is the number of steps needed for the MCMC used for evaluating the electron density for the 2 electron case.
[in] n_mcmc_steps points is the user defined number of evaluation points for the plotting grid.
n_ele is the number of electrons in the system
n_MCMC_steps is the number of steps needed for the MCMC used for evaluating the electron density for the 2 electron case.
[in] box box is the user defined size of the domain of the system wanting to be looked at.
[in] dof dof is the optimal degrees of freedom
Returns
Parameters
calc Ouput array which contains the results of the function
This allocates memory to the array based on the number of grid points defined by the user.
Uses wave_function_normalisation which returns the wave_norm_squared
This is for the 1 electron case, will just calculate and returns the wavefunction. Uses the wave_function function.
Track puts the result in the right place in the resulting output calc array.
Calculating the positions for input and gives coordinates between -box/2 to box/2
Returns the result of the wavefunction evaluated at one coordinate point using wave_function function.
Divides the result by the square root of the results from the wave_norm_squared result defined earlier.
For the 2 electron case, will calculate and return the electron density. Uses the electron_density function
Calculating the positions for input
Returns the result of the electron density evaluated at one coordinate point using electron_density function.
Divides the result by the results from the wave_norm_squared result defined earlier.
Returns a error print statement if the number of electrons is not defined.
Definition at line 18 of file calc.f90.
     IMPLICIT NONE
     INTEGER, PARAMETER :: dp=kind(1.0d0)
     INTEGER, INTENT(IN) :: points, n_ele, n_MCMC_steps
     real(dp),intent(in) :: box
     REAL(dp), DIMENSION(:), INTENT(IN) :: dof
     INTEGER :: array_len, track, i,j
     REAL(dp) :: a,b
     real(dp),dimension(3,2) :: box_in
     real(dp) :: wave_norm_squared
     REAL(dp), DIMENSION(:), ALLOCATABLE :: calc
     do i=1,3
       box_in(i,:) = [-box,box]
     end do
     array_len = (abs(points) + abs(points) + 1)**2
     ALLOCATE(calc(array_len))
     wave_norm_squared = wave_function_normalisation(box_in,dof,n_mcmc_steps)
     track = 0
     IF (n_ele .eq. 1) THEN
       DO i = -points, points
         DO j = -points, points
           track = track + 1
           a =  (real(i) / (abs(points) + abs(points)))*box
           b =  (real(j) / (abs(points) + abs(points)))*box
           calc(track) = wave_function([a,b,0.0d0], dof)
         END DO
       END DO
       calc = calc/sqrt(wave_norm_squared)
     ELSE IF (n_ele .eq. 2) THEN
       DO i = -points, points
         DO j = -points, points
           track = track + 1
           a =  (real(i) / (abs(points) + abs(points)))*box
           b =  (real(j) / (abs(points) + abs(points)))*box
           calc(track) = electron_density([a,b,0.0d0],box_in, dof, n_mcmc_steps )
         END DO
       END DO
       calc = calc/wave_norm_squared
     ELSE
       print*, 'Incorrect number of electrons in output calculation'
     END IF
References electron_density_functions::electron_density(), basis_functions::wave_function, and electron_density_functions::wave_function_normalisation().
Referenced by main_driver().