PX 915 Project Title/Name Here: mcmc Module Reference
mcmc Module Reference
Functions/Subroutines
real(dp) function, dimension(density_dimension), private mcmc_propose (x, s, density_dimension)
pure real(dp) function, private mcmc_log_prop_dist (x, y, s)
subroutine, private mcmc_accept (a, x, x_prop, log_rho, s, rho_x, rho_x_prop, dof_coefficients)
subroutine mcmc_sample (samples, log_rho, x_0, n_steps, n_burned, thinning_interval, s, e_code, dof_coefficients, density_dimension, average_accept, seed)
subroutine mcmc_adapt (s_out, log_rho, x_0, n_steps, s_0, e_code, s_max, s_min, memory, adapt_interval, dof_coefficients, density_dimension, seed)
Function/Subroutine Documentation
mcmc_accept()
subroutine, private mcmc::mcmc_accept (real(dp), intent(out) a, real(dp), dimension(:), intent(in) x, real(dp), dimension(:), intent(in) x_prop, log_rho, real(dp), intent(in) s, real(dp), intent(in), optional rho_x, real(dp), intent(out), optional rho_x_prop, real(dp), dimension(:), intent(in) dof_coefficients) private
Definition at line 63 of file MCMC.f90.
         !computes accpect prob in [0,1]
         implicit none
         real(dp), dimension(:), intent(in) :: x, x_prop
         real(dp), optional, intent(in) :: rho_x !log_rho(x) saved between runs to reduce calls
         real(dp), optional, intent(out) :: rho_x_prop !log_rho(x_prop)
         real(dp), dimension(:), intent(in) :: dof_coefficients
         real(dp), intent(in) :: s !stepsize parameter, contols log_prop_dist
         real(dp), intent(out) :: a
         real(dp) :: rho_x_, rho_x_prop_
         !decribes shape of input functions
         interface
             function log_rho(x, dof) result(out)
                 !log target dist
                 use shared_constants
                 real(dp), dimension(:), intent(in) :: x
                 real(dp), dimension(:), intent(in) :: dof
                 real(dp) :: out
             end function log_rho
         end interface
         if (present(rho_x)) then
             rho_x_ = rho_x
         else
             rho_x_ = log_rho(x, dof_coefficients)
         end if
         rho_x_prop_ = log_rho(x_prop, dof_coefficients)
         if (present(rho_x_prop)) rho_x_prop=rho_x_prop_
         a = (mcmc_log_prop_dist(x,x_prop,s)+rho_x_prop_)-(mcmc_log_prop_dist(x_prop,x,s)+rho_x_)
References mcmc_log_prop_dist().
Referenced by mcmc_adapt(), and mcmc_sample().
mcmc_adapt()
subroutine mcmc::mcmc_adapt (real(dp), intent(out) s_out, log_rho, real(dp), dimension(density_dimension), intent(in) x_0, integer, intent(in) n_steps, real(dp), intent(in) s_0, integer, intent(out) e_code, real(dp), intent(in) s_max, real(dp), intent(in) s_min, real(dp), intent(in) memory, integer, intent(in) adapt_interval, real(dp), dimension(:), intent(in) dof_coefficients, integer, intent(in) density_dimension, integer, dimension(:), intent(in), optional seed)
Definition at line 194 of file MCMC.f90.
         implicit none
         real(dp), intent(out) :: s_out
         integer, intent(in) :: n_steps, adapt_interval, density_dimension
         integer, intent(in), dimension(:), optional :: seed !the random seed, must have size>1
         real(dp), dimension(:), intent(in) :: dof_coefficients
         real(dp), intent(in) :: s_0 !intitial guess at step size
         real(dp), intent(in) :: s_max, s_min !bounds for search space in s
         real(dp), intent(in) :: memory !average memory of exponetial kernal
         real(dp), dimension(density_dimension), intent(in) :: x_0
         integer, intent(out) :: e_code
         real(dp), dimension(density_dimension) :: x,x_prop
         real(dp) :: a,a_unnorm,norm_cnst,a_ave,rand_sample,log_rho_x,log_rho_x_prop,s, factor, a_ave_
         real(dp) :: a_min, a_max !keep in close range about 0.235
         integer :: loop_index, adapt_count
         interface
             function log_rho(x, dof_coefficients) result(out)
                 !log target dist
                 use shared_constants
                 real(dp), dimension(:), intent(in) :: x
                 real(dp), dimension(:), intent(in) :: dof_coefficients
                 real(dp) :: out
             end function log_rho
         end interface
         a_min = 0.234_dp
         a_max = 0.236_dp
         x = x_0
         a_unnorm = 0.0_dp
         log_rho_x = log_rho(x_0,dof_coefficients)
         s=s_0
         norm_cnst=1.0_dp
         a_ave_=1.0_dp
         factor=sqrt(2.0_dp)
         !uses current random state if none is given
         if (present(seed)) then
             call random_seed(put=seed)
         end if
         do loop_index=1,n_steps
             x_prop = mcmc_propose(x,s,density_dimension)
             call mcmc_accept(a, x, x_prop, log_rho, s, log_rho_x, log_rho_x_prop,dof_coefficients)
             a = exp(a)
             call random_number(rand_sample)
             if (a>rand_sample) then
                 x = x_prop
                 log_rho_x = log_rho_x_prop !using datalog_rho_x_prop from last loop, saves calls to rho
                 !computing average acceptance rate, will want to have way of outputing at some point
                 a_unnorm = 1.0_dp + exp(-1.0_dp/memory)*a_unnorm
                 a_ave_= (1.0_dp+(loop_index-1)*a_ave_)/loop_index
             else
                 a_unnorm = exp(-1.0_dp/memory)*a_unnorm
                 a_ave_= ((loop_index-1)*a_ave_)/loop_index
             end if
             norm_cnst = 1.0_dp + exp(-1.0_dp/memory)*norm_cnst
             adapt_count = adapt_count+1
             if (adapt_count .ge. adapt_interval) then
                 if (a_ave_.le.0) then
                     if (a_ave_<0) then
                         e_code=e_code+2**1
                         print*, 'ERROR: Acceptance rate negative at:', loop_index
                         EXIT
                     end if
                     print*, 'WARNING: Acceptance rate 0 at:', loop_index
                 end if
                 adapt_count=0
                 a_ave = a_unnorm/norm_cnst
                 if (a_ave<a_min) then
                     s=s/factor
                     if (s<s_min) then
                         s=s_min
                     end if
                 else if (a_ave>a_max) then
                     s=s*factor
                     if (s>s_max) then
                         s=s_max
                     end if
                 end if
             end if
         end do
         s_out=s
         !e_code 0 => no error
         e_code=0
References mcmc_accept(), and mcmc_propose().
Referenced by loop_test(), main(), and main_driver().
mcmc_log_prop_dist()
pure real(dp) function, private mcmc::mcmc_log_prop_dist (real(dp), dimension(:), intent(in) x, real(dp), dimension(:), intent(in) y, real(dp), intent(in) s) private
Definition at line 50 of file MCMC.f90.
         !log liklihood x proposed at y
         implicit none
         real(dp), dimension(:), intent(in) :: x
         real(dp), dimension(:), intent(in) :: y
         real(dp), intent(in) :: s
         real(dp) :: out
         !unnormalised, as not needed, doing 1D step not nessesearily best but is easy
         out= -norm2(x-y)**2*(1/s)
Referenced by mcmc_accept().
mcmc_propose()
real(dp) function, dimension(density_dimension), private mcmc::mcmc_propose (real(dp), dimension(density_dimension), intent(in) x, real(dp), intent(in) s, integer, intent(in) density_dimension) private
Definition at line 20 of file MCMC.f90.
         implicit none
         integer, intent(in) :: density_dimension
         real(dp), dimension(density_dimension), intent(in) :: x
         real(dp), intent(in) :: s
         real(dp), dimension(2*((density_dimension+1)/2)) :: u !uniform random sample,
         !note the dimension is the nearest even number above the given dimension
         !integer division will autmatically round towards 0
         real(dp), dimension(density_dimension) :: xi !normal random sample
         real(dp), dimension(density_dimension) :: x_prop
         integer :: i
         !proposes, uses same dist as described in log_prop_dist
         !parametrising ititially with just a step size,
         !if proposal is changed, might need updated
         !implementing box muller to generate a normal
         call random_number(u)
         do i=1,density_dimension/2
             xi(i) = sqrt(-2.0_dp*log(u(i)))*cos(2.0_dp*pi*u(i*2))
             xi(i*2) = sqrt(-2.0_dp*log(u(i)))*sin(2.0_dp*pi*u(i*2))
         end do
         if (modulo(density_dimension,2).ne.0) then
             xi(density_dimension) = sqrt(-2.0_dp*log(u(density_dimension)))*cos(2.0_dp*pi*u(density_dimension+1))
         end if
         !basic GRW
         x_prop = x + s*xi
References shared_constants::pi.
Referenced by mcmc_adapt(), and mcmc_sample().
mcmc_sample()
subroutine mcmc::mcmc_sample (real(dp), dimension((n_steps-n_burned)/thinning_interval+1,density_dimension), intent(out) samples, log_rho, real(dp), dimension(density_dimension), intent(in) x_0, integer, intent(in) n_steps, integer, intent(in) n_burned, integer, intent(in) thinning_interval, real(dp), intent(in) s, integer, intent(out) e_code, real(dp), dimension(:), intent(in) dof_coefficients, integer, intent(in) density_dimension, real(dp), intent(out), optional average_accept, integer, dimension(:), intent(in), optional seed)
Definition at line 103 of file MCMC.f90.
         implicit none
         integer, intent(in) :: density_dimension
         integer, intent(in) :: n_steps
         integer, intent(in) :: n_burned
         integer, intent(in) :: thinning_interval
         integer, intent(in), dimension(:), optional :: seed !the random seed, must have size>1
         real(dp), dimension(:), intent(in) :: dof_coefficients
         real(dp), intent(in) :: s
         real(dp), dimension(density_dimension), intent(in) :: x_0
         integer, intent(out) :: e_code
         real(dp), intent(out), optional :: average_accept
         real(dp), dimension((n_steps-n_burned)/thinning_interval+1,density_dimension), intent(out) :: samples
         real(dp), dimension(density_dimension) :: x,x_prop
         real(dp) :: a,a_ave,rand_sample,log_rho_x,log_rho_x_prop
         integer :: loop_index,out_array_index,thinning_counter
         interface
             function log_rho(x, dof) result(out)
                 !log target dist
                 use shared_constants
                 real(dp), dimension(:), intent(in) :: x
                 real(dp), dimension(:), intent(in) :: dof
                 real(dp) :: out
             end function log_rho
         end interface
         !e_code 0 => no error
         e_code=0
         x = x_0
         out_array_index = 0
         thinning_counter = 0
         samples(1,:) = x_0
         a_ave = 0.0_dp
         log_rho_x = log_rho(x_0,dof_coefficients)
         !uses current random state if none is given
         if (present(seed)) then
             call random_seed(put=seed)
         end if
         do loop_index=1,n_steps
             x_prop = mcmc_propose(x,s,density_dimension)
             call mcmc_accept(a, x, x_prop, log_rho, s,log_rho_x,log_rho_x_prop, dof_coefficients)
             a = exp(a)
             call random_number(rand_sample)
             if (a>rand_sample) then
                 x = x_prop
                 log_rho_x = log_rho_x_prop !using datalog_rho_x_prop from last loop, saves calls to rho
                 !computing average acceptance rate, will want to have way of outputing at some point
                 a_ave = (1.0_dp/loop_index)*(a_ave*(loop_index-1.0_dp)+1.0_dp)
             else
                 a_ave = (1.0_dp/loop_index)*(a_ave*(loop_index-1))
             end if
             if (loop_index.ge.n_burned) then
                 thinning_counter = thinning_counter+1
             end if
             if (thinning_counter .ge. thinning_interval) then
                 out_array_index = out_array_index+1
                 if (out_array_index>(n_steps-n_burned)/thinning_interval) then
                     e_code = e_code+2**2
                     print*, 'ERROR: Output larger than output array', loop_index
                     exit
                 end if
                 if (a.ne.a) then
                     e_code=e_code+3**1
                     print*, 'ERROR: NAN acceptance at:', loop_index
                     EXIT
                 end if
                 if (a_ave.le.0) then
                     if (a_ave<0) then
                         e_code=e_code+2**1
                         print*, 'ERROR: Acceptance rate negative at:', loop_index
                         EXIT
                     end if
                     print*, 'WARNING: Acceptance rate 0 at:', loop_index
                 end if
                 samples(out_array_index,:) = x
                 thinning_counter=0
             end if
         end do
         if (present(average_accept)) then
             average_accept = a_ave
         end if
References mcmc_accept(), and mcmc_propose().
Referenced by loop_test(), main(), and main_driver().