PX 915 Project Title/Name Here: basis_functions Module Reference
basis_functions Module Reference
Wavefunction, hamiltonian and basis set choice.
Data Types
interface wave_function_interface
Functions/Subroutines
subroutine initialise_basis (n_electrons_in, n_basis_functions_per_atom_in, n_atoms_in, atom_coords_in, n_Jastrow_in, fd_length_in, Jastrow_b_length_in, Jastrow_d_length_in, proton_numbers_in, basis_type_in)
Initialisation routine.
subroutine deinitialise_basis
Dinitialisation routine.
real(dp) function wave_function_slater_1s (position, dof_coefficients)
Single Electron wavefunction: slater 1s basis.
real(dp) function reduced_hamiltonian_slater_1s (position, dof_coefficients)
Single Electron Reduced Hamiltonian: slater 1s basis.
real(dp) function discrete_laplacian_reduced (position, h, dofs)
Finite Difference Reduced Laplacian Computes finite difference approximation to the reduced laplacian $(\nabla^2\psi)/\psi$.
real(dp) function wave_function_2_electrons (position, dof_coefficients)
Wavefunction for 2 electrons.
real(dp) function reduced_hamiltonian_2_electrons (position, dof_coefficients)
Reduced Hamiltonian for 2 electrons.
subroutine mno_allocate (n_terms)
Allocate parameters for Jastrow factor.
real(dp) function log_density (position, dof_coefficients)
Log of the Probability Density.
real(dp) function wave_function_sto3g (position, dof_coefficients)
Single Electron wavefunction: gaussian sto3g basis.
real(dp) function reduced_hamiltonian_sto3g (position, dof_coefficients)
Single Electron Reduced Hamiltonian: gaussian sto3g basis.
Variables
procedure(wave_function_interface), pointer wave_function
procedure(wave_function_interface), pointer reduced_hamiltonian
logical, protected initialised = .false.
integer, protected n_electrons
integer, protected n_basis_functions_per_atom
integer, protected n_atoms
real(dp), dimension(:,:), allocatable, protected atom_coords
integer, protected n_jastrow_dofs
real(dp), protected fd_h
real(dp), protected b_length
real(dp), protected d_length
real(dp), dimension(:), allocatable, protected proton_numbers
integer, protected basis_type
integer, protected number_dofs
integer, protected n_space_dims
real(dp), dimension(:,:), allocatable, protected dof_bounds
integer, protected n_dofs_per_atom
integer, protected n_dofs_no_jastrow
integer, dimension(:,:), allocatable, protected mno_parameters
procedure(wave_function_interface), pointer wave_function_single
Detailed Description
Wavefunction, hamiltonian and basis set choice.
This module contains functions that define the hamiltonian that specifies the problem and the basis set being used. Makes significant use of module variables defined in an initialisation subroutine. This allocates 2 function pointers using wave_function_interface
wave_function
reduced_hamiltonian
Parameters
position a real(dp) array of electron coordinates
dof_coefficients a real(dp) array of degree of freedom (dof) parameters These are the only functions that should be used outside of the module.
Function/Subroutine Documentation
deinitialise_basis()
subroutine basis_functions::deinitialise_basis
Dinitialisation routine.
MUST be run at the end of main program to deallocate module variables.
Definition at line 267 of file basis_functions.f90.
     implicit none
     if (initialised) deallocate(dof_bounds,atom_coords,proton_numbers)
     if (allocated(mno_parameters)) deallocate(mno_parameters)
     initialised = .false.
References atom_coords, dof_bounds, initialised, mno_parameters, and proton_numbers.
Referenced by bond_length_driver(), main(), and main_driver().
discrete_laplacian_reduced()
real(dp) function basis_functions::discrete_laplacian_reduced (real(dp), dimension(:), intent(in) position, real(dp), intent(in) h, real(dp), dimension(:), intent(in) dofs)
Finite Difference Reduced Laplacian Computes finite difference approximation to the reduced laplacian $(\nabla^2\psi)/\psi$.
Uses that $f''(x)/f(x) =((f(x+h)+f(x-h))/f(x)-2)/(h^2)+O(h^2)$ (*)
Parameters
[in] position Space coordinate of electrons
[in] h Finite difference lengthscale
[in] dofs Values of the dofs
Definition at line 368 of file basis_functions.f90.
     implicit none
     real(dp) :: discrete_Laplacian_reduced
     real(dp), dimension(:), intent(in) :: position
     real(dp), intent(in) :: h
     real(dp), dimension(:), intent(in) :: dofs
     integer :: i ! Loop variable
     real(dp), dimension(:,:), allocatable :: delta ! temporary array for vector displacements
     ! Initialise and bounds tests
     if (.not.(initialised)) then
       print *, "Error, basis not initialised"
       stop
     end if
     if (size(position).ne.n_space_dims) then
       print *, "Error, wrong space dimension, got", size(position), "wanted", n_space_dims
       stop
     end if
     if (size(dofs).ne.number_dofs) then
       print *, "Error, wrong number of dofs, got", size(dofs), "wanted", number_dofs
       stop
     end if
     ! Create matrix of cartesian basis vectors of length h. Set as 0 initially, h added during main loop
     allocate(delta(n_space_dims,n_space_dims))
     delta = 0.0_dp ! Matrix assignment
     discrete_laplacian_reduced = 0.0_dp
     do i = 1, n_space_dims ! Loop over space dimensions
       delta(i,i) = h
       discrete_laplacian_reduced = discrete_laplacian_reduced &
       ! Following (*), sum of (f(x+h)+f(x-h)) in all space dimensions
       + wave_function(position + delta(:,i), dofs) + wave_function(position - delta(:,i), dofs)
     end do
     ! Following (*), divide by $f(x)$, and subtract 2 for each space dimension
     discrete_laplacian_reduced = discrete_laplacian_reduced/wave_function(position ,dofs) - 2*n_space_dims
     ! Following (*), divide by h^2
     discrete_laplacian_reduced = discrete_laplacian_reduced/(h**2)
     ! deallocate temporary array
     deallocate(delta)
References initialised, n_space_dims, number_dofs, and wave_function.
Referenced by reduced_hamiltonian_2_electrons().
initialise_basis()
subroutine basis_functions::initialise_basis (integer, intent(in) n_electrons_in, integer, intent(in) n_basis_functions_per_atom_in, integer, intent(in) n_atoms_in, real(dp), dimension(:,:), intent(in) atom_coords_in, integer, intent(in), optional n_Jastrow_in, real(dp), intent(in), optional fd_length_in, real(dp), intent(in), optional Jastrow_b_length_in, real(dp), intent(in), optional Jastrow_d_length_in, real(dp), dimension(:), intent(in), optional proton_numbers_in, integer, intent(in), optional basis_type_in)
Initialisation routine.
Must be run at the start of the main program, after user input. This defines the problem and selects the basis being used. It allocates module variables and procedure pointers.
Parameters
[in] n_electrons_in Number of electrons
[in] n_basis_functions_per_atom_in Number of linear terms in the single-electron wavefunction per atom
[in] n_atoms_in Number of atoms
[in] atom_coords_in Coordinates of the atoms. Shape (3,n_atoms)
[in] n_jastrow_in Number of dofs in the Jastrow (interaction) term
[in] fd_length_in Lengthscale of the finite difference code
[in] jastrow_b_length_in Inverse lengthscale of nuclear-electron interaction
[in] jastrow_d_length_in Inverse lengthscale of electron-electron interaction
[in] proton_numbers_in Proton Numbers of atoms
[in] basis_type_in integer code for type of basis. Codes are listed in shared_constants.f90
Definition at line 69 of file basis_functions.f90.
     implicit none
     ! Required Parameters
     integer, intent(in) :: n_electrons_in
     integer, intent(in) :: n_basis_functions_per_atom_in
     integer, intent(in) :: n_atoms_in
     real(dp), dimension(:,:), intent(in) :: atom_coords_in
     ! Optional Paramters
     integer, optional, intent(in) :: n_Jastrow_in
     real(dp), optional, intent(in) :: fd_length_in
     real(dp), optional, intent(in) :: Jastrow_b_length_in
     real(dp), optional, intent(in) :: Jastrow_d_length_in
     real(dp), dimension(:), optional, intent(in) :: proton_numbers_in
     integer, optional, intent(in) :: basis_type_in
     ! Internal Variables
     integer :: i ! Loop variable
     integer :: n_dofs_per_basis_function ! number of dofs per linear term of the wavefunction. Always 2 for slater and Gaussian
     ! Check not already initialised
     if (initialised) then
       print *, "Error, cannot initialise basis twice"
       stop
     end if
     if (n_atoms_in <= 0) then
       print*,"Error, number of atoms must be positive"
       stop
     end if
     if ((n_atoms_in .ne. 1).and.(n_atoms_in .ne. 2)) then
       print*,"Error, only 1 or 2 atoms supported"
       stop
     end if
     n_atoms = n_atoms_in
     ! Check and allocate the atom coordinates
     if (size(atom_coords_in,2) .ne. n_atoms_in ) then
       print*,"Error, wrong number of atoms"
       stop
     end if
     if (size(atom_coords_in,1) .ne. 3 ) then
       print*,"Error, wrong dimension of atom coordinates"
       stop
     end if
     allocate(atom_coords(3,size(atom_coords_in,2)))
     atom_coords = atom_coords_in
     ! Check and assign other required inputs
     if (n_basis_functions_per_atom_in <= 0) then
       print*,"Error, number of basis functions per atom must be positive"
       stop
     end if
     n_basis_functions_per_atom = n_basis_functions_per_atom_in
     if ((n_electrons_in .ne. 1).and.(n_electrons_in .ne. 2)) then
       print*,"Error, number of electrons must be 1 or 2"
       stop
     end if
     n_electrons = n_electrons_in
     n_space_dims = 3*n_electrons
     ! Check and assign optional paramters
     if (present(n_jastrow_in)) then
       n_jastrow_dofs = n_jastrow_in
     else
       n_jastrow_dofs = 7 ! Default Value
     end if
     if (present(fd_length_in)) then
       if (fd_length_in>0.00009) then
         fd_h = fd_length_in
       else
         print*, "Error, finite difference length must be at least 0.0001"
         stop
       end if
     else
       fd_h = 0.01_dp ! Default Value
     end if
     if (present(jastrow_b_length_in)) then
       if (jastrow_b_length_in>0.05) then
         b_length = jastrow_b_length_in
       else
         print*, "Error, Jastrow b length must be positive"
         stop
       end if
     else
       b_length = 1.0_dp ! Default value
     end if
     if (present(jastrow_d_length_in)) then
       if (jastrow_d_length_in>0.05) then
         d_length = jastrow_d_length_in
       else
         print*, "Error, Jastrow d length must be positive"
         stop
       end if
     else
       d_length = 1.0_dp ! Default value
     end if
     allocate(proton_numbers(n_atoms))
     if (present(proton_numbers_in)) then
       if (size(proton_numbers_in)==n_atoms) then
         proton_numbers = proton_numbers_in
       else
         print*, "Error, mismatch in number of atoms and proton numbers"
         stop
       end if
     else
       proton_numbers = 1.0_dp ! Default value is hydrogen
     end if
     if(present(basis_type_in)) then
       basis_type = basis_type_in
     else
       basis_type = slater_1s_code !Default basis set
     end if
     ! Assign individual electron wavefunction with input basis set
     select case(basis_type)
     case (slater_1s_code)
       wave_function_single => wave_function_slater_1s
       reduced_hamiltonian => reduced_hamiltonian_slater_1s
     case (sto_3g_code)
       wave_function_single => wave_function_sto3g
       reduced_hamiltonian => reduced_hamiltonian_sto3g
     case default
       print *, "Basis type not recognised"
       stop
     end select
     ! Set number of dofs per basis function. This may change for future choices of basis sets
     n_dofs_per_basis_function = 2
     n_dofs_per_atom = n_dofs_per_basis_function * n_basis_functions_per_atom
     n_dofs_no_jastrow = n_dofs_per_atom * n_atoms
     ! Assignments for one electron, slater type orbital
     if (n_electrons_in .eq. 1) then
       number_dofs = n_dofs_per_atom * n_atoms
       allocate(dof_bounds(number_dofs,2))
       ! Assign dof bounds for single electron part
       ! Ordering here is for 2 dofs per basis function, in pairs, first linear dof then width dof
       do i = 1, n_basis_functions_per_atom*n_atoms ! Loop over pairs of dofs
           dof_bounds(2*i-1,:)=[-1.5_dp,1.5_dp] ! Linear coeffs defaults -1.5 to 1.5
           dof_bounds(2*i,:)=[0.1_dp,1.5_dp]   ! width positive, up to 1.5
       end do
       ! Assign wave_function pointer. Ham pointer already assigned
       wave_function => wave_function_single
     end if
     ! Assignments for 2 electrons, slater type orbital
     if (n_electrons_in .eq. 2) then
       ! Allocate the mno parameters that determine the form of Jastrow term
       call mno_allocate(n_jastrow_dofs)
       number_dofs = n_dofs_per_atom * n_atoms + n_jastrow_dofs
       allocate(dof_bounds(number_dofs,2))
       ! Assign dof bounds
       ! Ordering here is for 2 dofs per basis function, first linear cooef then width coeff
       do i = 1,n_basis_functions_per_atom*n_atoms ! Loop over pairs of dofs
           dof_bounds(2*i-1,:)=[-1.5_dp,1.5_dp] ! Linear coeffs bounds -1.5 to 1.5
           dof_bounds(2*i,:)=[0.1_dp,1.5_dp]   ! width positive, up to 1.5
       end do
       if (n_jastrow_dofs.ne.0) then
         do i = n_dofs_per_atom*n_atoms+1, number_dofs
           dof_bounds(i,:) = [-1.5_dp,1.5_dp] ! Jastrow dofs bounds -1.5 to 1.5
         end do
       end if
       ! Assign the procedure pointers
       wave_function => wave_function_2_electrons
       reduced_hamiltonian => reduced_hamiltonian_2_electrons
     end if
     ! Set initialised flag, which is tested in the routines
     initialised = .true.
References atom_coords, b_length, basis_type, d_length, dof_bounds, fd_h, initialised, mno_allocate(), n_atoms, n_basis_functions_per_atom, n_dofs_no_jastrow, n_dofs_per_atom, n_electrons, n_jastrow_dofs, n_space_dims, number_dofs, proton_numbers, reduced_hamiltonian, reduced_hamiltonian_2_electrons(), reduced_hamiltonian_slater_1s(), reduced_hamiltonian_sto3g(), shared_constants::slater_1s_code, shared_constants::sto_3g_code, wave_function, wave_function_2_electrons(), wave_function_single, wave_function_slater_1s(), and wave_function_sto3g().
Referenced by bond_length_driver(), main(), and main_driver().
log_density()
real(dp) function basis_functions::log_density (real(dp), dimension(:), intent(in) position, real(dp), dimension(:), intent(in) dof_coefficients)
Log of the Probability Density.
For the MCMC integration.
Parameters
[in] position Space coordinate of electrons
[in] dof_coefficients Values of the dofs
Definition at line 540 of file basis_functions.f90.
     implicit none
     real(dp) :: log_density
     real(dp), dimension(:), intent(in) :: position
     real(dp), dimension(:), intent(in) :: dof_coefficients
     log_density = 2*log(abs(wave_function(position,dof_coefficients)))
References wave_function.
Referenced by bond_length_driver(), and main_driver().
mno_allocate()
subroutine basis_functions::mno_allocate (integer, intent(in) n_terms)
Allocate parameters for Jastrow factor.
Allocates the paramters that determine type of Jastrow function. Sizes 0,3,7,9 supported. Functions are from Schmidt and Moskowitz 1990
Parameters
[in] n_terms Number of terms in Jastrow correlation function
Definition at line 497 of file basis_functions.f90.
     implicit none
     integer,intent(in) :: n_terms
     select case (n_terms)
       case (0)
         n_jastrow_dofs = 0
       case (3)
         allocate(mno_parameters(3,3))
         mno_parameters(:,1) = [0,0,1]
         mno_parameters(:,2) = [0,0,2]
         mno_parameters(:,3) = [2,0,0]
         n_jastrow_dofs = 3
       case (7)
         allocate(mno_parameters(3,7))
         mno_parameters(:,1) = [0,0,1]
         mno_parameters(:,2) = [0,0,2]
         mno_parameters(:,3) = [0,0,3]
         mno_parameters(:,4) = [0,0,4]
         mno_parameters(:,5) = [2,0,0]
         mno_parameters(:,6) = [3,0,0]
         mno_parameters(:,7) = [4,0,0]
         n_jastrow_dofs = 7
       case (9)
         allocate(mno_parameters(3,9))
         mno_parameters(:,1) = [0,0,1]
         mno_parameters(:,2) = [0,0,2]
         mno_parameters(:,3) = [0,0,3]
         mno_parameters(:,4) = [0,0,4]
         mno_parameters(:,5) = [2,0,0]
         mno_parameters(:,6) = [3,0,0]
         mno_parameters(:,7) = [4,0,0]
         mno_parameters(:,8) = [2,2,0]
         mno_parameters(:,9) = [2,0,2]
         n_jastrow_dofs = 9
       case default
         print *, "Jastrow term of size:", n_terms, "not supported"
         stop
     end select
References mno_parameters, and n_jastrow_dofs.
Referenced by initialise_basis().
reduced_hamiltonian_2_electrons()
real(dp) function basis_functions::reduced_hamiltonian_2_electrons (real(dp), dimension(:), intent(in) position, real(dp), dimension(:), intent(in) dof_coefficients)
Reduced Hamiltonian for 2 electrons.
Computes the reduced Hamiltonian $(H\psi)/\psi$ for 2 electrons. Uses discrete_Laplacian_reduced in this module.
Parameters
[in] position Space coordinate of electrons
[in] dof_coefficients Values of the dofs
Definition at line 454 of file basis_functions.f90.
     implicit none
     real(dp) :: reduced_hamiltonian_2_electrons
     real(dp), dimension(:), intent(in) :: position
     real(dp), dimension(:), intent(in) :: dof_coefficients
     integer :: j ! Loop variable
     ! Initialise and bounds tests
     if (.not.(initialised)) then
       print *, "Error, basis not initialised"
       stop
     end if
     if (size(position).ne.n_space_dims) then
       print *, "Error, wrong space dimension, got", size(position), "wanted", n_space_dims
       stop
     end if
     if (size(dof_coefficients).ne.number_dofs) then
       print *, "Error, wrong number of dofs, got", size(dof_coefficients), "wanted", number_dofs
       stop
     end if
     ! Reduced Kinetic energy and electron-electron reduced potential energy
     ! $-0.5\nabla^2\psi$ +1/r, r distance between electrons
     reduced_hamiltonian_2_electrons = -0.5_dp*discrete_laplacian_reduced(position, fd_h, dof_coefficients) &
       + 1.0_dp /norm2(position(1:3)-position(4:6))
     ! Reduced electron-nuclear potential energy, -1/r, r distance from electron to atom
     do j = 1, n_atoms ! Loop over atoms
       reduced_hamiltonian_2_electrons  = reduced_hamiltonian_2_electrons  &
           -proton_numbers(j) /norm2(position(1:3)-atom_coords(:,j))&
           -proton_numbers(j) /norm2(position(4:6)-atom_coords(:,j))
     end do
     if (n_atoms ==2) then
       reduced_hamiltonian_2_electrons  = reduced_hamiltonian_2_electrons  &
       +proton_numbers(1)*proton_numbers(2) /norm2(atom_coords(:,1)-atom_coords(:,2))
     end if
References atom_coords, discrete_laplacian_reduced(), fd_h, initialised, n_atoms, n_space_dims, number_dofs, and proton_numbers.
Referenced by initialise_basis().
reduced_hamiltonian_slater_1s()
real(dp) function basis_functions::reduced_hamiltonian_slater_1s (real(dp), dimension(:), intent(in) position, real(dp), dimension(:), intent(in) dof_coefficients)
Single Electron Reduced Hamiltonian: slater 1s basis.
Reduced Hamiltonian $(H\psi)/\psi$ for 1 electron, with slater 1s type orbital Uses centered_slater_1s_laplacian in component_functions.f90 Used only for 1 electron problems.
Parameters
[in] position Space coordinate of electrons
[in] dof_coefficients Values of the dofs
loop over atoms
loop over linear terms in wavefunction
Definition at line 315 of file basis_functions.f90.
     implicit none
     real(dp) :: reduced_hamiltonian_slater_1s
     real(dp), dimension(:), intent(in) :: position
     real(dp), dimension(:), intent(in) :: dof_coefficients
     integer :: i, j ! Loop variables
     ! Initialise and bounds tests
     if (.not.(initialised)) then
       print *, "Error, basis not initialised"
       stop
     end if
     if (size(position).ne.n_space_dims) then
       print *, "Error, wrong space dimension, got", size(position), "wanted", n_space_dims
       stop
     end if
     if (size(dof_coefficients).ne.number_dofs) then
       print *, "Error, wrong number of dofs, got", size(dof_coefficients), "wanted", number_dofs
       stop
     end if
     reduced_hamiltonian_slater_1s = 0.0_dp
     ! Kinetic energy term $-0.5\nabla^2\psi$
     ! This wavefunction is linear, and it is easy to compute this analytically
     do j = 0, n_atoms-1
       do i= 1,n_basis_functions_per_atom
         reduced_hamiltonian_slater_1s = reduced_hamiltonian_slater_1s &
           -0.5_dp * dof_coefficients( 2*i-1 +j*n_dofs_per_atom) & ! linear coefficient dof
             *centered_slater_1s_laplacian(position-atom_coords(:,j+1), & ! position relative to atom
               dof_coefficients( 2*i +j*n_dofs_per_atom ) ) ! lengthscale dof
       end do
     end do
     ! Divide by the wavefunction to get reduced laplacian $(-0.5\nabla^2\psi)/\psi$
     reduced_hamiltonian_slater_1s = reduced_hamiltonian_slater_1s/wave_function_slater_1s(position,dof_coefficients)
     ! Potential energy, already reduced, so no wavefunction in this
     do j = 1, n_atoms ! loop over atoms
     reduced_hamiltonian_slater_1s = reduced_hamiltonian_slater_1s &
       -proton_numbers(j) /norm2(position-atom_coords(:,j)) ! -1/r, r distance from electron to atom
     end do
     if (n_atoms ==2) then
       reduced_hamiltonian_slater_1s = reduced_hamiltonian_slater_1s &
       +proton_numbers(1)*proton_numbers(2) /norm2(atom_coords(:,1)-atom_coords(:,2))
     end if
References atom_coords, component_functions::centered_slater_1s_laplacian(), initialised, n_atoms, n_basis_functions_per_atom, n_dofs_per_atom, n_space_dims, number_dofs, proton_numbers, and wave_function_slater_1s().
Referenced by initialise_basis().
reduced_hamiltonian_sto3g()
real(dp) function basis_functions::reduced_hamiltonian_sto3g (real(dp), dimension(:), intent(in) position, real(dp), dimension(:), intent(in) dof_coefficients)
Single Electron Reduced Hamiltonian: gaussian sto3g basis.
Reduced Hamiltonian $(H\psi)/\psi$ for 1 electron, with basic gaussian sto3g type orbital Uses centered_gaussian_laplacian in component_functions.f90 Used only for 1 electron problems.
Parameters
[in] position Space coordinate of electrons
[in] dof_coefficients Values of the dofs
Definition at line 594 of file basis_functions.f90.
     implicit none
     real(dp) :: reduced_hamiltonian_sto3g
     real(dp), dimension(:), intent(in) :: position
     real(dp), dimension(:), intent(in) :: dof_coefficients
     integer :: i, j ! Loop variables
     ! Initialise and bounds tests
     if (.not.(initialised)) then
       print *, "Error, basis not initialised"
       stop
     end if
     if (size(position).ne.n_space_dims) then
       print *, "Error, wrong space dimension, got", size(position), "wanted", n_space_dims
       stop
     end if
     if (size(dof_coefficients).ne.number_dofs) then
       print *, "Error, wrong number of dofs, got", size(dof_coefficients), "wanted", number_dofs
       stop
     end if
     reduced_hamiltonian_sto3g = 0.0_dp
     ! Kinetic energy term $-0.5\nabla^2\psi$
     ! This wavefunction is linear, and it is easy to compute this analytically
     do j = 0, n_atoms-1 ! loop over atoms
       do i= 1,n_basis_functions_per_atom ! loop over linear terms in wavefunction
         reduced_hamiltonian_sto3g = reduced_hamiltonian_sto3g &
           -0.5_dp * dof_coefficients( 2*i-1 +j*n_dofs_per_atom) & ! linear coefficient dof
             *centered_gaussian_laplacian(position-atom_coords(:,j+1), & ! position relative to atom
               dof_coefficients( 2*i +j*n_dofs_per_atom ) ) ! lengthscale dof
       end do
     end do
     ! Divide by the wavefunction to get reduced laplacian $(-0.5\nabla^2\psi)/\psi$
     reduced_hamiltonian_sto3g = reduced_hamiltonian_sto3g/wave_function_sto3g(position,dof_coefficients)
     ! Potential energy, already reduced, so no wavefunction in this
     do j = 0, n_atoms-1 ! loop over atoms
       reduced_hamiltonian_sto3g = reduced_hamiltonian_sto3g &
       -1.0_dp /norm2(position-atom_coords(:,j+1)) !-1/r, r distance from electron to atom
     end do
     if (n_atoms ==2) then
       reduced_hamiltonian_sto3g = reduced_hamiltonian_sto3g &
       +proton_numbers(1)*proton_numbers(2) /norm2(atom_coords(:,1)-atom_coords(:,2))
     end if
References atom_coords, component_functions::centered_gaussian_laplacian(), initialised, n_atoms, n_basis_functions_per_atom, n_dofs_per_atom, n_space_dims, number_dofs, proton_numbers, and wave_function_sto3g().
Referenced by initialise_basis().
wave_function_2_electrons()
real(dp) function basis_functions::wave_function_2_electrons (real(dp), dimension(:), intent(in) position, real(dp), dimension(:), intent(in) dof_coefficients)
Wavefunction for 2 electrons.
Uses subprocedure correlation_function in component_functions.f90 Uses the function pointer wave_function_single
Parameters
[in] position Space coordinate of electrons
[in] dof_coefficients Values of the dofs
Definition at line 417 of file basis_functions.f90.
     implicit none
     real(dp) :: wave_function_2_electrons
     real(dp), dimension(:), intent(in) :: position
     real(dp), dimension(:), intent(in) :: dof_coefficients
     ! Initialise and bounds tests
     if (.not.(initialised)) then
       print *, "Error, basis not initialised"
       stop
     end if
     if (size(position).ne.n_space_dims) then
       print *, "Error, wrong space dimension, got", size(position), "wanted", n_space_dims
       stop
     end if
     if (size(dof_coefficients).ne.number_dofs) then
       print *, "Error, wrong number of dofs, got", size(dof_coefficients), "wanted", number_dofs
       stop
     end if
     ! Slater determinant (trivial for 2 electron spin up/down pair)
     ! position(1:3) is coords of first electron, (4:6) is the second. dof(:n_no_jastrow) are the relevant dofs
     wave_function_2_electrons = wave_function_single(position(1:3),dof_coefficients(:n_dofs_no_jastrow))&
     * wave_function_single(position(4:6),dof_coefficients(:n_dofs_no_jastrow))
     ! Multiply by correlation function. This is the Jastrow term. dof(n_dofs_no_Jastrow+1:) are relevant terms
     if (n_jastrow_dofs.ne.0) then
     wave_function_2_electrons = &
       correlation_function(atom_coords,position,mno_parameters,dof_coefficients(n_dofs_no_jastrow+1:),&
       b_length,d_length)*wave_function_2_electrons
     end if
References atom_coords, b_length, component_functions::correlation_function(), d_length, initialised, mno_parameters, n_dofs_no_jastrow, n_jastrow_dofs, n_space_dims, number_dofs, and wave_function_single.
Referenced by initialise_basis().
wave_function_slater_1s()
real(dp) function basis_functions::wave_function_slater_1s (real(dp), dimension(:), intent(in) position, real(dp), dimension(:), intent(in) dof_coefficients)
Single Electron wavefunction: slater 1s basis.
Uses centered_slater_1s in component_functions.f90
Parameters
[in] position Space coordinate of electron
[in] dof_coefficients Values of the dofs
Definition at line 276 of file basis_functions.f90.
     implicit none
     real(dp) :: wave_function_slater_1s
     real(dp), dimension(:), intent(in) :: position
     real(dp), dimension(:), intent(in) :: dof_coefficients
     integer :: i, j ! loop variables
     ! Initialise and bounds tests
     if (.not.(initialised)) then
       print *, "Error, basis not initialised"
       stop
     end if
     if (size(position).ne.3) then
       print *, "Error, wrong space dimension, got", size(position), "wanted 3"
       stop
     end if
     if (size(dof_coefficients).ne.n_dofs_no_jastrow) then
       print *, "Error, wrong number of dofs, got", size(dof_coefficients), "wanted", n_dofs_no_jastrow
       stop
     end if
     ! Wavefunction is sum over linear terms with 2 dofs each - a linear coefficient and a lengthscale
     wave_function_slater_1s = 0.0_dp
     do j = 0, n_atoms-1 ! loop over atoms
       do i= 1, n_basis_functions_per_atom ! loop over linear terms in wavefunction
         wave_function_slater_1s = wave_function_slater_1s + &
           dof_coefficients( 2*i-1 + j*n_dofs_per_atom )& ! linear coefficient dof
             *centered_slater_1s(position-atom_coords(:,j+1), & ! position relative to atom
               dof_coefficients( 2*i + j*n_dofs_per_atom  ) ) ! lengthscale dof
       end do
     end do
References atom_coords, component_functions::centered_slater_1s(), initialised, n_atoms, n_basis_functions_per_atom, n_dofs_no_jastrow, and n_dofs_per_atom.
Referenced by initialise_basis(), and reduced_hamiltonian_slater_1s().
wave_function_sto3g()
real(dp) function basis_functions::wave_function_sto3g (real(dp), dimension(:), intent(in) position, real(dp), dimension(:), intent(in) dof_coefficients)
Single Electron wavefunction: gaussian sto3g basis.
Uses centered_gaussian in component_functions.f90
Parameters
[in] position Space coordinate of electron
[in] dof_coefficients Values of the dofs
Definition at line 554 of file basis_functions.f90.
     implicit none
     real(dp) :: wave_function_sto3g
     real(dp), dimension(:), intent(in) :: position
     real(dp), dimension(:), intent(in) :: dof_coefficients
     integer :: i, j ! loop variables
     ! Initialise and bounds tests
     if (.not.(initialised)) then
       print *, "Error, basis not initialised"
       stop
     end if
     if (size(position).ne.3) then
       print *, "Error, wrong space dimension, got", size(position), "wanted 3"
       stop
     end if
     if (size(dof_coefficients).ne.n_dofs_no_jastrow) then
       print *, "Error, wrong number of dofs, got", size(dof_coefficients), "wanted", n_dofs_no_jastrow
       stop
     end if
     ! Wavefunction is sum over linear terms with 2 dofs each - a linear coefficient and a lengthscale
     wave_function_sto3g = 0.0_dp
     do j = 0, n_atoms-1 ! loop over atoms
       do i= 1, n_basis_functions_per_atom ! loop over linear terms in wavefunction
         wave_function_sto3g = wave_function_sto3g + &
           dof_coefficients( 2*i-1 + j*n_dofs_per_atom )& ! linear coefficient dof
             *centered_gaussian(position-atom_coords(:,j+1), & ! position relative to atom
               dof_coefficients( 2*i + j*n_dofs_per_atom  ) ) ! lengthscale dof
       end do
     end do
References atom_coords, component_functions::centered_gaussian(), initialised, n_atoms, n_basis_functions_per_atom, n_dofs_no_jastrow, and n_dofs_per_atom.
Referenced by initialise_basis(), and reduced_hamiltonian_sto3g().
Variable Documentation
atom_coords
real(dp), dimension(:,:), allocatable, protected basis_functions::atom_coords
Definition at line 42 of file basis_functions.f90.
   real(dp), protected, allocatable, dimension(:,:) :: atom_coords ! Coordinates of the atoms. Shape (3,n_atoms)
Referenced by deinitialise_basis(), initialise_basis(), reduced_hamiltonian_2_electrons(), reduced_hamiltonian_slater_1s(), reduced_hamiltonian_sto3g(), wave_function_2_electrons(), wave_function_slater_1s(), and wave_function_sto3g().
b_length
real(dp), protected basis_functions::b_length
Definition at line 45 of file basis_functions.f90.
   real(dp), protected :: b_length ! Inverse lengthscale of nuclear-electron interaction
Referenced by initialise_basis(), and wave_function_2_electrons().
basis_type
integer, protected basis_functions::basis_type
Definition at line 48 of file basis_functions.f90.
   integer, protected :: basis_type ! integer code for type of basis. In shared_constants module
Referenced by initialise_basis().
d_length
real(dp), protected basis_functions::d_length
Definition at line 46 of file basis_functions.f90.
   real(dp), protected :: d_length ! Inverse lengthscale of electron-electron interaction
Referenced by initialise_basis(), and wave_function_2_electrons().
dof_bounds
real(dp), dimension(:,:), allocatable, protected basis_functions::dof_bounds
Definition at line 52 of file basis_functions.f90.
   real(dp), allocatable, dimension(:,:), protected :: dof_bounds ! Default bounds for the possible dof values
Referenced by bond_length_driver(), deinitialise_basis(), stoch_grad::grad_accent(), initialise_basis(), main(), main_driver(), and stoch_grad::stoch_grad_init().
fd_h
real(dp), protected basis_functions::fd_h
Definition at line 44 of file basis_functions.f90.
   real(dp), protected :: fd_h ! Lengthscale of the finite difference code
Referenced by initialise_basis(), and reduced_hamiltonian_2_electrons().
initialised
logical, protected basis_functions::initialised = .false.
Definition at line 36 of file basis_functions.f90.
   logical, protected :: initialised = .false. ! Flag set by initialisation routine, checked by other routines
Referenced by deinitialise_basis(), discrete_laplacian_reduced(), initialise_basis(), reduced_hamiltonian_2_electrons(), reduced_hamiltonian_slater_1s(), reduced_hamiltonian_sto3g(), wave_function_2_electrons(), wave_function_slater_1s(), and wave_function_sto3g().
mno_parameters
integer, dimension(:,:), allocatable, protected basis_functions::mno_parameters
Definition at line 57 of file basis_functions.f90.
   integer, protected, allocatable, dimension(:,:) :: mno_parameters ! Parameters that specify the particular choice of Jastrow term
Referenced by deinitialise_basis(), mno_allocate(), and wave_function_2_electrons().
n_atoms
integer, protected basis_functions::n_atoms
Definition at line 41 of file basis_functions.f90.
   integer, protected :: n_atoms ! Number of atoms
Referenced by initialise_basis(), reduced_hamiltonian_2_electrons(), reduced_hamiltonian_slater_1s(), reduced_hamiltonian_sto3g(), wave_function_slater_1s(), and wave_function_sto3g().
n_basis_functions_per_atom
integer, protected basis_functions::n_basis_functions_per_atom
Definition at line 40 of file basis_functions.f90.
   integer, protected :: n_basis_functions_per_atom ! Number of linear terms in the single-electron wavefunction per atom
Referenced by initialise_basis(), reduced_hamiltonian_slater_1s(), reduced_hamiltonian_sto3g(), wave_function_slater_1s(), and wave_function_sto3g().
n_dofs_no_jastrow
integer, protected basis_functions::n_dofs_no_jastrow
Definition at line 56 of file basis_functions.f90.
   integer, protected :: n_dofs_no_Jastrow ! Number of dofs without Jastrow term, for convenience
Referenced by initialise_basis(), wave_function_2_electrons(), wave_function_slater_1s(), and wave_function_sto3g().
n_dofs_per_atom
integer, protected basis_functions::n_dofs_per_atom
Definition at line 55 of file basis_functions.f90.
   integer, protected :: n_dofs_per_atom ! Number of dofs per atom, for convenience
Referenced by initialise_basis(), reduced_hamiltonian_slater_1s(), reduced_hamiltonian_sto3g(), wave_function_slater_1s(), and wave_function_sto3g().
n_electrons
integer, protected basis_functions::n_electrons
Definition at line 39 of file basis_functions.f90.
   integer, protected :: n_electrons ! Number of electrons
Referenced by initialise_basis().
n_jastrow_dofs
integer, protected basis_functions::n_jastrow_dofs
Definition at line 43 of file basis_functions.f90.
   integer, protected :: n_Jastrow_dofs ! Number of dofs in the Jastrow (interaction) term
Referenced by initialise_basis(), mno_allocate(), and wave_function_2_electrons().
n_space_dims
integer, protected basis_functions::n_space_dims
Definition at line 51 of file basis_functions.f90.
   integer, protected :: n_space_dims ! Number of space dimensions, 3*n_electrons, for convenience
Referenced by bond_length_driver(), discrete_laplacian_reduced(), initialise_basis(), main_driver(), reduced_hamiltonian_2_electrons(), reduced_hamiltonian_slater_1s(), reduced_hamiltonian_sto3g(), wave_function_2_electrons(), and electron_density_functions::wave_function_normalisation().
number_dofs
integer, protected basis_functions::number_dofs
Definition at line 50 of file basis_functions.f90.
   integer, protected :: number_dofs ! Total number of degrees of freedom (dofs) in the wavefunction
Referenced by bond_length_driver(), discrete_laplacian_reduced(), initialise_basis(), main(), main_driver(), reduced_hamiltonian_2_electrons(), reduced_hamiltonian_slater_1s(), reduced_hamiltonian_sto3g(), and wave_function_2_electrons().
proton_numbers
real(dp), dimension(:), allocatable, protected basis_functions::proton_numbers
Definition at line 47 of file basis_functions.f90.
   real(dp),dimension(:),allocatable, protected :: proton_numbers ! Proton Numbers of atoms
Referenced by deinitialise_basis(), initialise_basis(), reduced_hamiltonian_2_electrons(), reduced_hamiltonian_slater_1s(), and reduced_hamiltonian_sto3g().
reduced_hamiltonian
procedure(wave_function_interface), pointer basis_functions::reduced_hamiltonian
Definition at line 21 of file basis_functions.f90.
   procedure(wave_function_interface), pointer :: reduced_hamiltonian
Referenced by bond_length_driver(), initialise_basis(), main(), and main_driver().
wave_function
procedure(wave_function_interface), pointer basis_functions::wave_function
Definition at line 20 of file basis_functions.f90.
   procedure(wave_function_interface), pointer :: wave_function
Referenced by calculations::calc(), discrete_laplacian_reduced(), electron_density_functions::electron_density(), initialise_basis(), log_density(), log_rho_mod::log_rho(), and electron_density_functions::wave_function_normalisation().
wave_function_single
procedure(wave_function_interface), pointer basis_functions::wave_function_single
Definition at line 60 of file basis_functions.f90.
   procedure(wave_function_interface), pointer :: wave_function_single
Referenced by initialise_basis(), and wave_function_2_electrons().