PX 915 Project Title/Name Here: biased_optim Module Reference
biased_optim Module Reference
Data Types
interface bi_op_init
Functions/Subroutines
logical function find_restart_file ()
subroutine bi_op_init_constant_mean (param_init_data, energy_init_data, n_data_in, n_dof_in, ker_var, ker_lengthscale, constant_mean_prior, optim_rate_para, optim_no_samples, n_threads, n_loops_to_do)
subroutine bi_op_init_arb_mean (param_init_data, energy_init_data, n_data_in, n_dof_in, ker_var, ker_lengthscale, mean_prior_func, mean_prior_dx, optim_rate_para, optim_no_samples, n_threads, n_loops_to_do)
real(dp) function, dimension(threads, n_dof) bi_op_step (param_update_data, energy_update_data, n_new_data, threads, seed, n_cycles)
Variables
logical gp_uptodate = .False.
Function/Subroutine Documentation
bi_op_init_arb_mean()
subroutine biased_optim::bi_op_init_arb_mean (real(dp), dimension(n_data_in, n_dof_in), intent(in) param_init_data, real(dp), dimension(n_data_in), intent(in) energy_init_data, integer, intent(in) n_data_in, integer, intent(in) n_dof_in, real(dp), intent(in) ker_var, real(dp), intent(in) ker_lengthscale, procedure(mean_func_interface) mean_prior_func, procedure(mean_func_interface_dx) mean_prior_dx, real(dp), intent(in) optim_rate_para, integer, intent(in) optim_no_samples, integer, intent(in) n_threads, integer, intent(inout) n_loops_to_do)
Definition at line 132 of file Biased_Optim.f90.
        implicit none
        integer, intent(inout) :: n_loops_to_do
        integer, intent(in) :: n_data_in, n_dof_in, optim_no_samples,n_threads
        real(dp), dimension(n_data_in, n_dof_in), intent(in) :: param_init_data
        real(dp), dimension(n_data_in), intent(in) :: energy_init_data
        real(dp), intent(in) :: ker_var, ker_lengthscale,  optim_rate_para
        procedure(mean_func_interface) :: mean_prior_func
        procedure(mean_func_interface_dx) :: mean_prior_dx
        n_dof = n_dof_in
        gamma = optim_rate_para
        no_samples=optim_no_samples
        call gp_init(mean_prior_func, mean_prior_dx, ker_var, ker_lengthscale, param_init_data, energy_init_data,&
         n_data_in, n_dof_in, n_threads)
        gp_uptodate = .false.
        current_best_e = minval(energy_init_data)
References gp_uptodate.
bi_op_init_constant_mean()
subroutine biased_optim::bi_op_init_constant_mean (real(dp), dimension(n_data_in, n_dof_in), intent(in) param_init_data, real(dp), dimension(n_data_in), intent(in) energy_init_data, integer, intent(in) n_data_in, integer, intent(in) n_dof_in, real(dp), intent(in) ker_var, real(dp), intent(in) ker_lengthscale, real(dp), intent(in) constant_mean_prior, real(dp), intent(in) optim_rate_para, integer, intent(in) optim_no_samples, integer, intent(in) n_threads, integer, intent(inout) n_loops_to_do)
Definition at line 82 of file Biased_Optim.f90.
         implicit none
         integer, intent(inout) :: n_loops_to_do
         integer, intent(in) :: n_data_in, n_dof_in, optim_no_samples,n_threads
         real(dp), dimension(n_data_in, n_dof_in), intent(in) :: param_init_data
         real(dp), dimension(n_data_in), intent(in) :: energy_init_data
         real(dp), intent(in) :: ker_var, ker_lengthscale, constant_mean_prior, optim_rate_para
         integer gp_n_data, gp_n_dof, n_cycles
         real(dp) :: kernel_var, kernal_inv_length
         real(dp), dimension(:,:), allocatable :: param_data
         real(dp), dimension(:), allocatable :: E_data
         real(dp), dimension(:,:), allocatable :: param_pres, param_cov
         real(dp), dimension(:), allocatable :: data_mean
         if (find_restart_file()) then
             call read_restart_file_sizes(gp_n_data, gp_n_dof)
             allocate(param_data(gp_n_data, gp_n_dof))
             allocate(e_data(gp_n_data))
             allocate(param_pres(gp_n_data, gp_n_data))
             allocate(param_cov(gp_n_data, gp_n_data))
             allocate(data_mean(gp_n_data))
             call read_restart_file_data(n_cycles, no_samples, current_best_e,&
             constant_mean_value, kernel_var, gamma, kernal_inv_length,&
             gp_n_data, e_data, gp_n_data, data_mean, gp_n_data, gp_n_data, param_pres, &
             gp_n_data, gp_n_data, param_pres, gp_n_data, gp_n_dof, param_data)
             n_dof = gp_n_dof
             call gp_restart(gp_n_data, gp_n_dof,kernel_var, kernal_inv_length,&
             param_data, e_data,param_pres, param_cov, data_mean, constant_mean,&
              zero_func, n_threads)
             gp_uptodate = .false.
             current_best_e = minval(e_data)
             n_loops_to_do=n_loops_to_do-(n_cycles-1)
         else
             constant_mean_value = constant_mean_prior
             gamma = optim_rate_para
             no_samples=optim_no_samples
             n_dof = n_dof_in
             call gp_init(constant_mean, zero_func, ker_var, ker_lengthscale, param_init_data, energy_init_data, n_data_in,&
              n_dof_in,n_threads)
             gp_uptodate = .false.
             current_best_e = minval(energy_init_data)
         end if
References find_restart_file(), gp_surrogate::gp_restart(), and gp_uptodate.
bi_op_step()
real(dp) function, dimension(threads,n_dof) biased_optim::bi_op_step (real(dp), dimension(n_new_data, n_dof), intent(in) param_update_data, real(dp), dimension(n_new_data), intent(in) energy_update_data, integer, intent(in) n_new_data, integer, intent(in) threads, integer, dimension(:), intent(in) seed, integer, intent(in) n_cycles)
Definition at line 155 of file Biased_Optim.f90.
         implicit none
         integer, intent(in) :: n_new_data, n_cycles
         integer, intent(in) :: threads !number of threads/restarts goes here
         integer, dimension(:), intent(IN):: seed
         real(dp), dimension(n_new_data, n_dof), intent(in) :: param_update_data
         real(dp), dimension(n_new_data), intent(in) :: energy_update_data
         real(dp), dimension(threads,threads, n_dof) ::  per_thread_best_loc
         real(dp), dimension(0:threads) ::  m,z
         real(dp), dimension(0:threads,0:threads) ::  c
         real(dp), dimension(threads) ::  per_thread_best_qei
         real(dp), dimension(threads,n_dof) :: best_locs
         real(dp) :: best_E_in_batch
         integer :: i, j, best_restart, n_seed, gp_n_data, gp_n_dof
         real(dp) :: kernel_var, kernal_inv_length
         real(dp), dimension(:,:), allocatable :: param_data
         real(dp), dimension(:), allocatable :: E_data
         real(dp), dimension(:,:), allocatable :: param_pres, param_cov
         real(dp), dimension(:), allocatable :: data_mean
         if (gp_uptodate) then
             call gp_update(param_update_data,  energy_update_data, n_new_data, 'F')
         end if
         !updating best point
         best_e_in_batch = minval(energy_update_data)
         if (best_e_in_batch < current_best_e) current_best_e=best_e_in_batch
         print*, current_best_e
         call stoch_grad_init(threads,current_best_e,seed)
         ! !doing the restart file thing
         ! call gp_return_size_data(gp_n_data, gp_n_dof)
         ! allocate(param_data(gp_n_data, gp_n_dof))
         ! allocate(E_data(gp_n_data))
         ! allocate(param_pres(gp_n_data, gp_n_data))
         ! allocate(param_cov(gp_n_data, gp_n_data))
         ! allocate(data_mean(gp_n_data))
         ! call gp_return_state_data(kernel_var, kernal_inv_length,  param_data, E_data,&
         ! param_pres, param_cov, data_mean)
         ! !assuming calling order of (scalars(rank 0),..., vector_dim, vector(rank 1),..., matrix_dim_1,matrix_dim2, matrix(rank 2))
         ! call write_restart_file(gp_n_data, gp_n_dof,n_cycles,no_samples, current_best_E,&
         ! constant_mean_value, gamma, kernel_var, kernal_inv_length, &
         ! gp_n_data, E_data, gp_n_data, data_mean, gp_n_data, gp_n_data, param_pres, &
         ! gp_n_data, gp_n_data, param_pres, gp_n_data, gp_n_dof, param_data)
         !doing grad_accent, can be parrallel
         !$OMP parallel do default(shared) private(i,m,c,z)
         do i=1,threads
             !the "no change" state
             z=0.0_dp
             m=0.0_dp
             call grad_accent(n_points(i,:,:),threads,no_samples,gamma,per_thread_best_loc(i,:,:))
             m(1:threads) = current_best_e-gp_mu_post(per_thread_best_loc(i,:,:), threads)
             call get_cholesky(c, gp_k_post_same_x(per_thread_best_loc(i,:,:), threads))
             c= -c
             !c = -get_cholesky(gp_k_post_same_x(per_thread_best_loc(i,:,:), threads))
             do j=1,no_samples
                 z(1:threads) = gaussian(threads)
                 per_thread_best_qei(i) =  maxval(m + matmul(c, z))
             end do
         end do
         best_restart = maxloc(per_thread_best_qei,dim=1)
         best_locs = per_thread_best_loc(best_restart,:,:)
         gp_uptodate = .true.
References gp_surrogate::gp_k_post_same_x(), gp_surrogate::gp_mu_post(), gp_surrogate::gp_update(), gp_uptodate, stoch_grad::grad_accent(), stoch_grad::n_points, and stoch_grad::stoch_grad_init().
Referenced by main(), and main_driver().
find_restart_file()
logical function biased_optim::find_restart_file
Definition at line 72 of file Biased_Optim.f90.
         implicit none
         logical :: retval
         retval=.false.
Referenced by bi_op_init_constant_mean().
Variable Documentation
gp_uptodate
logical biased_optim::gp_uptodate = .False.
Definition at line 13 of file Biased_Optim.f90.
     logical :: GP_uptodate = .false.
Referenced by bi_op_init_arb_mean(), bi_op_init_constant_mean(), and bi_op_step().