PX 915: Variational Quantum Monte Carlo - LATIN: gp_surrogate Module Reference
gp_surrogate Module Reference
Gaussian process surrogate submodules and functions.
Data Types
interface cov_kernal_dx_1_interface
interface cov_kernal_interface
interface cov_kernal_xx_dx_interface
interface gp_init
general initialisation function, see gp_init_gausscov
interface gp_k_post
function for postieror covairance kernal use in format x_1, x_2, x1_dim, x2_dim for cov(x_1,x_2) use in format x, x_dim for cov(x,x)
interface mean_func_interface
interface mean_func_interface_dx
Functions/Subroutines
subroutine gp_init_gausscov (mean_prior, mean_prior_dx, ker_var, ker_length, param_data_in, E_data_in, n_data_in, n_dof_in, n_threads_in)
intialises with a gaussian covariance
subroutine gp_init_arbcov (mean_prior, cov_prior, param_data_in, E_data_in, n_data_in, n_dof_in)
do not use, don't have a function for the dervatives of the kernal/mean
real(dp) function, dimension(x_dim) gp_mu_post (x, x_dim)
posterior mean
real(dp) function gp_mu_post_dx (x, dim)
derivative of the posterior mean, wrt dimension dim
real(dp) function, dimension(x_dim, n_dof) gp_mu_post_grad (x, x_dim, only)
derivative of the posterior mean, needed for stoch_grad
real(dp) function, dimension(x_dim, x_dim) gp_k_post_same_x (x, x_dim)
specific function for cov(x,x), see gp_k_post
real(dp) function, dimension(x1_dim, x2_dim) gp_k_post_diff_x (x1, x2, x1_dim, x2_dim)
specific function for cov(x_1,x_2), see gp_k_post
subroutine gp_post_k_grad (X, x_dim, out)
grad of the posterior covariance, evaluated at X of size x_dim,n_dof, needed for stoch_grad
subroutine gp_update (param_data_in_top, E_data_in_top, n_top, Algo_choice)
update routine for adding data to gp
subroutine gp_debug_print_state ()
prints all scalar stae variables, size of all array state variables, and min and max stored energy
subroutine gp_exit ()
deallocates state variables
subroutine gp_min_stored (min_params, min_E)
for finding minimum of the energy and associated parameter space point, from stored data
subroutine gp_return_size_data (n_data_out, n_dof_out)
returns the integers that control the size of the state variables
subroutine gp_return_state_data (kernel_var_out, kernal_inv_length_out, param_data_out, E_data_out, param_pres_out, param_cov_out, data_mean_out)
for acessing a copy of the state variables, they are returned to the intent(out) parameter with the corresponding name
subroutine gp_restart (n_data_in, n_dof_in, kernel_var_in, kernal_inv_length_in, param_data_in, E_data_in, param_pres_in, param_cov_in, data_mean_in, mean_prior, mean_prior_dx, n_threads_in)
sets a state from inputed data, intended for use with restart files.
Variables
procedure(mean_func_interface_dx), pointer mu_prior_dx => null()
Detailed Description
Gaussian process surrogate submodules and functions.
Function/Subroutine Documentation
gp_debug_print_state()
subroutine gp_surrogate::gp_debug_print_state
prints all scalar stae variables, size of all array state variables, and min and max stored energy
Definition at line 639 of file GP_surrogate.f90.
     implicit none
     print*, "init=", init
     print*, "n_data=", n_data
     print*, "n_dof=", n_dof
     print*, "kernel_var=", kernel_var
     print*, "kernal_inv_length=", kernal_inv_length
     print*, "shape of param_data=", shape(param_data)
     print*, "shape of E_data=", shape(e_data)
     print*, "shape of param_pres=", shape(param_pres)
     print*, "shape of param_cov=", shape(param_cov)
     print*, "shape of data_mean=", shape(data_mean)
     print*, "min energy", minval(e_data)
     print*, "max energy", maxval(e_data)
Referenced by main().
gp_exit()
subroutine gp_surrogate::gp_exit
deallocates state variables
Definition at line 658 of file GP_surrogate.f90.
     implicit none
         !deallocating state variables
         deallocate(param_data,e_data,param_pres, param_cov,data_mean)
         !deallocating pointers
         nullify(mu_prior,mu_prior_dx ,k_prior ,k_prior_dx_1_i ,k_prior_xx_dx_i ,gp_k_post_xx_d_x_i)
References mu_prior_dx.
Referenced by main().
gp_init_arbcov()
subroutine gp_surrogate::gp_init_arbcov (procedure(mean_func_interface) mean_prior, procedure(cov_kernal_interface) cov_prior, real(dp), dimension(n_data_in,n_dof_in), intent(in) param_data_in, real(dp), dimension(n_data_in), intent(in) E_data_in, integer, intent(in) n_data_in, integer, intent(in) n_dof_in)
do not use, don't have a function for the dervatives of the kernal/mean
Definition at line 194 of file GP_surrogate.f90.
         implicit none
         procedure(mean_func_interface) :: mean_prior
         procedure(cov_kernal_interface) :: cov_prior
         integer, intent(in) :: n_data_in, n_dof_in
         real(dp), dimension(n_data_in,n_dof_in), intent(in) :: param_data_in
         real(dp), dimension(n_data_in), intent(in) :: E_data_in
         !work and ipiv are needed for lapack call, have no useful info
         integer :: i,j
         !setting priors
         mu_prior => mean_prior
         k_prior => cov_prior
         !setting data
         n_data = n_data_in
         n_dof = n_dof_in
         allocate(param_data(n_data,n_dof))
         allocate(e_data(n_data))
         e_data = e_data_in
         param_data = param_data_in
         allocate(param_cov(n_data,n_data))
         allocate(param_pres(n_data,n_data))
         !finds covarience for new data
         do i=1,n_data
             do j=1,i
                 !is symmteric, this reduces calls
                 param_cov(i,j) = k_prior(param_data(i,:), param_data(j,:))
                 param_cov(j,i) = param_cov(i,j)
             end do
         end do
         !compute inverse of cov (precsion)
         param_pres = param_cov
         call svd_inverse(param_pres,  n_data)
         allocate(data_mean(n_data))
         !updating the prior mean list
         do i=1,n_data
             data_mean(i) = mu_prior(param_data(i,:))
         end do
         init = .true.
gp_init_gausscov()
subroutine gp_surrogate::gp_init_gausscov (procedure(mean_func_interface) mean_prior, procedure(mean_func_interface_dx) mean_prior_dx, real(dp), intent(in) ker_var, real(dp), intent(in) ker_length, real(dp), dimension(n_data_in,n_dof_in), intent(in) param_data_in, real(dp), dimension(n_data_in), intent(in) E_data_in, integer, intent(in) n_data_in, integer, intent(in) n_dof_in, integer, intent(in) n_threads_in)
intialises with a gaussian covariance
Definition at line 133 of file GP_surrogate.f90.
         implicit none
         procedure(mean_func_interface) :: mean_prior
         procedure(mean_func_interface_dx) :: mean_prior_dx
         integer, intent(in) :: n_data_in, n_dof_in,n_threads_in
         real(dp), intent(in) :: ker_var, ker_length
         real(dp), dimension(n_data_in,n_dof_in), intent(in) :: param_data_in
         real(dp), dimension(n_data_in), intent(in) :: E_data_in
         integer :: i,j
         n_threads=n_threads_in
         !setting prior parameters
         kernel_var = ker_var
         kernal_inv_length = 1.0_dp/ker_length
         !setting priors
         mu_prior => mean_prior
         k_prior => gaussian_kernel
         !derivatives of priors, needed for SGA step later
         mu_prior_dx => mean_prior_dx
         k_prior_dx_1_i => gaussian_kernel_dx_1_i
         k_prior_xx_dx_i => zero_func
         gp_k_post_xx_d_x_i => zero_func !prior 0=>post 0, this saves having to evaluate (or write, until support is expanded) code to get the 0
         !setting data
         n_data = n_data_in
         n_dof = n_dof_in
         allocate(param_data(n_data,n_dof))
         allocate(e_data(n_data))
         e_data = e_data_in
         param_data = param_data_in
         allocate(param_cov(n_data,n_data))
         allocate(param_pres(n_data,n_data))
         !finds covarience for new data
         do i=1,n_data
             do j=1,i
                 !is symmteric, this reduces calls
                 param_cov(i,j) = k_prior(param_data(i,:), param_data(j,:))
                 param_cov(j,i) = param_cov(i,j)
             end do
         end do
         !compute inverse of cov (precsion)
         param_pres = param_cov
         call svd_inverse(param_pres,  n_data)
         allocate(data_mean(n_data))
         !updating the prior mean list
         do i=1,n_data
             data_mean(i) = mu_prior(param_data(i,:))
         end do
         init = .true.
References mu_prior_dx.
gp_k_post_diff_x()
real(dp) function, dimension(x1_dim,x2_dim) gp_surrogate::gp_k_post_diff_x (real(dp), dimension(x1_dim,n_dof), intent(in) x1, real(dp), dimension(x2_dim,n_dof), intent(in) x2, integer, intent(in) x1_dim, integer, intent(in) x2_dim)
specific function for cov(x_1,x_2), see gp_k_post
Definition at line 356 of file GP_surrogate.f90.
         implicit none
         integer, intent(in) :: x1_dim, x2_dim
         real(dp), dimension(x1_dim,n_dof), intent(in) :: x1 !param space point
         real(dp), dimension(x2_dim,n_dof), intent(in) :: x2 !param space point
         real(dp), dimension(x1_dim,x2_dim) :: out, x1_cov_x2
         real(dp), dimension(n_data,x2_dim) :: data_cov_x2
         real(dp), dimension(x1_dim,n_data) :: x1_cov_data
         integer :: i,j
         if (.not. init) then
             print*,'not intialised'
             stop
         end if
         do i=1,x2_dim
             do j=1,n_data
                 data_cov_x2(j,i) = k_prior(x2(i,:), param_data(j,:))
             end do
         end do
         do i=1,x1_dim
             do j=1,n_data
                 x1_cov_data(i,j) = k_prior(param_data(j,:),x1(i,:))
             end do
         end do
         do i=1,x1_dim
             do j=1,x2_dim
                 x1_cov_x2(i,j) = k_prior(x1(i,:), x2(j,:))
             end do
         end do
        out = x1_cov_x2 + matmul(matmul(x1_cov_data,param_pres),data_cov_x2)
gp_k_post_same_x()
real(dp) function, dimension(x_dim,x_dim) gp_surrogate::gp_k_post_same_x (real(dp), dimension(x_dim,n_dof), intent(in) x, integer, intent(in) x_dim)
specific function for cov(x,x), see gp_k_post
Definition at line 322 of file GP_surrogate.f90.
         implicit none
         integer, intent(in) :: x_dim
         real(dp), dimension(x_dim,n_dof), intent(in) :: x !param space point
         real(dp), dimension(x_dim,x_dim) :: out, x_cov_x
         real(dp), dimension(x_dim,n_data) :: x_cov_data
         real(dp), dimension(n_data,x_dim) :: data_cov_x
         integer :: i,j
         if (.not. init) then
             print*,'not intialised'
             stop
         end if
         do i=1,x_dim
             do j=1,n_data
                 data_cov_x(j,i) = k_prior(param_data(j,:), x(i,:))
             end do
         end do
         x_cov_data = transpose(data_cov_x)
         do i=1,x_dim
             do j=1,i
                 !is symmteric, this reduces calls
                 x_cov_x(i,j) = k_prior(x(i,:), x(j,:))
                 x_cov_x(j,i) = x_cov_x(i,j)
             end do
         end do
        out = x_cov_x + matmul(matmul(x_cov_data,param_pres),data_cov_x)
Referenced by biased_optim::bi_op_step().
gp_min_stored()
subroutine gp_surrogate::gp_min_stored (real(dp), dimension(n_dof), intent(out) min_params, real(dp), intent(out) min_E)
for finding minimum of the energy and associated parameter space point, from stored data
Definition at line 724 of file GP_surrogate.f90.
         implicit none
         real(dp), dimension(n_dof), intent(out) :: min_params
         real(dp), intent(out) :: min_E
         integer :: minloc_E
         minloc_e = minloc(e_data,1)
         min_e = e_data(minloc_e)
         min_params = param_data(minloc_e,:)
Referenced by main().
gp_mu_post()
real(dp) function, dimension(x_dim) gp_surrogate::gp_mu_post (real(dp), dimension(x_dim,n_dof), intent(in) x, integer, intent(in) x_dim)
posterior mean
Definition at line 244 of file GP_surrogate.f90.
         implicit none
         integer, intent(in) :: x_dim
         real(dp), dimension(x_dim,n_dof), intent(in) :: x
         real(dp), dimension(x_dim) :: out
         real(dp), dimension(x_dim) :: x_means
         real(dp), dimension(x_dim,n_data) :: x_cov_data
         integer :: i,j
         if (.not. init) then
             print*,'not intialised'
             stop
         end if
         do i=1,x_dim
             x_means(i) = mu_prior(x(i,:))
             do j=1,n_data
                 x_cov_data(i,j) = k_prior(x(i,:), param_data(j,:))
             end do
         end do
        out = x_means + matmul(matmul(x_cov_data,param_pres),(e_data-data_mean))
Referenced by biased_optim::bi_op_step(), gradient_estimator::m_vector(), and main().
gp_mu_post_dx()
real(dp) function gp_surrogate::gp_mu_post_dx (real(dp), dimension(n_dof), intent(in) x, integer, intent(in) dim)
derivative of the posterior mean, wrt dimension dim
Definition at line 270 of file GP_surrogate.f90.
         implicit none
         !only gets evaluated at one point
         integer, intent(in) :: dim
         real(dp), dimension(n_dof), intent(in) :: x
         real(dp) :: out
         real(dp), dimension(1,n_data) :: x_cov_data_dx
         real(dp), dimension(1) :: prod_temp
         integer :: j
         do j=1,n_data
             x_cov_data_dx(1,j) = k_prior_dx_1_i(x,param_data(j,:),dim)
         end do
         prod_temp = matmul(x_cov_data_dx,matmul(param_pres,(e_data-data_mean)))
         out = mu_prior_dx(x, dim) + prod_temp(1)
References mu_prior_dx.
Referenced by gp_mu_post_grad().
gp_mu_post_grad()
real(dp) function, dimension(x_dim,n_dof) gp_surrogate::gp_mu_post_grad (real(dp), dimension(x_dim,n_dof), intent(in) x, integer, intent(in) x_dim, integer, intent(in), optional only)
derivative of the posterior mean, needed for stoch_grad
Definition at line 291 of file GP_surrogate.f90.
         implicit none
         !row i contain the gradient of mu wrt data_i
         integer, intent(in) :: x_dim
         integer, intent(in), optional :: only
         real(dp), dimension(x_dim,n_dof), intent(in) :: x !param space point
         real(dp), dimension(x_dim,n_dof) :: out
         integer :: i,j
         if (.not. init) then
             print*,'not intialised'
             stop
         end if
         out=0
         if (present(only)) then
             do j=1,n_dof
                 out(only,j) = gp_mu_post_dx(x(only,:),j)
             end do
         else
             do i=1,x_dim
                 do j=1,n_dof
                     out(i,j) = gp_mu_post_dx(x(i,:),j)
                 end do
             end do
         end if
References gp_mu_post_dx().
Referenced by gradient_estimator::combine_f_grad_k(), and main().
gp_post_k_grad()
subroutine gp_surrogate::gp_post_k_grad (real(dp), dimension(x_dim,n_dof), intent(in) X, integer, intent(in) x_dim, real(dp), dimension(x_dim,x_dim,x_dim,n_dof), intent(out) out)
grad of the posterior covariance, evaluated at X of size x_dim,n_dof, needed for stoch_grad
Parameters
[in] x_dim size of X
[in] x point to evaluate at
[out] out the output matrix, size (x_dim,x_dim,x_dim,n_dof)
Definition at line 422 of file GP_surrogate.f90.
         !triple nested for loops are slow,try not to call often
         implicit none
         integer,intent(in) :: x_dim
         real(dp), dimension(x_dim,n_dof), intent(in) :: X
         real(dp), dimension(x_dim,x_dim,x_dim,n_dof),intent(out) ::  out
         integer :: i,j,l
         if (.not. init) then
             print*,'not intialised'
             stop
         end if
         do i=1,x_dim
             do j=1,x_dim
                 if (i/=j) then
                     do l=1,n_dof
                         out(i,j,j,l) = gp_k_post_d_x_1_i(x(j,:),x(i,:),l)
                         out(i,j,i,l) = gp_k_post_d_x_1_i(x(i,:),x(j,:),l)
                     end do
                 else
                     do l=1,n_dof
                         out(i,j,i,l) = gp_k_post_xx_d_x_i(x(i,:),l)
                     end do
                 end if
             end do
         end do
Referenced by gradient_estimator::combine_f_grad_k(), and main().
gp_restart()
subroutine gp_surrogate::gp_restart (integer, intent(in) n_data_in, integer, intent(in) n_dof_in, real(dp), intent(in) kernel_var_in, real(dp), intent(in) kernal_inv_length_in, real(dp), dimension(n_data_in,n_dof_in), intent(in) param_data_in, real(dp), dimension(n_data_in), intent(in) E_data_in, real(dp), dimension(n_data_in,n_data_in), intent(in) param_pres_in, real(dp), dimension(n_data_in,n_data_in), intent(in) param_cov_in, real(dp), dimension(n_data_in), intent(in) data_mean_in, procedure(mean_func_interface) mean_prior, procedure(mean_func_interface_dx) mean_prior_dx, integer, intent(in) n_threads_in)
sets a state from inputed data, intended for use with restart files.
Variables must correspond to named counterpart
Definition at line 770 of file GP_surrogate.f90.
         implicit none
         integer, intent(in) :: n_data_in, n_dof_in,n_threads_in
         real(dp), intent(in) :: kernel_var_in, kernal_inv_length_in
         real(dp), dimension(n_data_in,n_dof_in), intent(in):: param_data_in
         real(dp), dimension(n_data_in), intent(in) :: E_data_in
         real(dp), dimension(n_data_in,n_data_in), intent(in) :: param_pres_in, param_cov_in
         real(dp), dimension(n_data_in), intent(in) :: data_mean_in
         procedure(mean_func_interface) :: mean_prior
         procedure(mean_func_interface_dx) :: mean_prior_dx
         n_data = n_data_in
         n_dof = n_dof_in
         n_threads = n_threads_in
         kernel_var=kernel_var_in
         kernal_inv_length=kernal_inv_length_in
         allocate(param_data(n_data,n_dof))
         param_data=param_data_in
         allocate(e_data(n_data))
         e_data=e_data_in
         allocate(param_pres(n_data,n_data))
         param_pres=param_pres_in
         allocate(param_cov(n_data,n_data))
         param_cov=param_cov_in
         allocate(data_mean(n_data))
         data_mean=data_mean_in
         mu_prior => mean_prior
         k_prior => gaussian_kernel
         !derivatives of priors, needed for SGA step later
         mu_prior_dx => mean_prior_dx
         k_prior_dx_1_i => gaussian_kernel_dx_1_i
         k_prior_xx_dx_i => zero_func
         gp_k_post_xx_d_x_i => zero_func
         init = .true.
References mu_prior_dx.
Referenced by biased_optim::bi_op_init_constant_mean().
gp_return_size_data()
subroutine gp_surrogate::gp_return_size_data (integer, intent(out) n_data_out, integer, intent(out) n_dof_out)
returns the integers that control the size of the state variables
Definition at line 738 of file GP_surrogate.f90.
     implicit none
     integer,intent(out) :: n_data_out,  n_dof_out
     n_data_out = n_data
     n_dof_out = n_dof
gp_return_state_data()
subroutine gp_surrogate::gp_return_state_data (real(dp), intent(out) kernel_var_out, real(dp), intent(out) kernal_inv_length_out, real(dp), dimension(n_data,n_dof), intent(out) param_data_out, real(dp), dimension(n_data), intent(out) E_data_out, real(dp), dimension(n_data,n_data), intent(out) param_pres_out, real(dp), dimension(n_data,n_data), intent(out) param_cov_out, real(dp), dimension(n_data), intent(out) data_mean_out)
for acessing a copy of the state variables, they are returned to the intent(out) parameter with the corresponding name
Definition at line 749 of file GP_surrogate.f90.
         implicit none
         real(dp), intent(out)  :: kernel_var_out, kernal_inv_length_out
         real(dp), dimension(n_data,n_dof), intent(out):: param_data_out
         real(dp), dimension(n_data), intent(out) :: E_data_out
         real(dp), dimension(n_data,n_data), intent(out) :: param_pres_out, param_cov_out
         real(dp), dimension(n_data), intent(out) :: data_mean_out
         kernel_var_out = kernel_var
         kernal_inv_length_out = kernal_inv_length
         param_data_out = param_data
         e_data_out = e_data
         param_pres_out = param_pres
         param_cov_out = param_cov
         data_mean_out = data_mean
gp_update()
subroutine gp_surrogate::gp_update (real(dp), dimension(n_top,n_dof), intent(in) param_data_in_top, real(dp), dimension(n_top), intent(in) E_data_in_top, integer, intent(in) n_top, character(len=1), intent(in) Algo_choice)
update routine for adding data to gp
Definition at line 453 of file GP_surrogate.f90.
         integer, intent(in) :: n_top
         real(dp), dimension(n_top,n_dof), intent(in) :: param_data_in_top
         real(dp), dimension(n_top), intent(in) :: E_data_in_top
         character(len=1), intent(in) :: Algo_choice
         select case (algo_choice)
         case ("F")
             call gp_update_full_svd(param_data_in_top, e_data_in_top, n_top)
         case ("U")
             call gp_update_woodbury_block_update(param_data_in_top, e_data_in_top, n_top)
         case default
             print*, "please make a valid algorithm choice"
         end select
Referenced by biased_optim::bi_op_step(), and main().
Variable Documentation
mu_prior_dx
procedure (mean_func_interface_dx), pointer gp_surrogate::mu_prior_dx => null()
Definition at line 18 of file GP_surrogate.f90.
     procedure(mean_func_interface_dx),pointer :: mu_prior_dx => null()
Referenced by gp_exit(), gp_init_gausscov(), gp_mu_post_dx(), and gp_restart().