PX 915 Project Title/Name Here: shared_constants Module Reference
shared_constants Module Reference
Variables
integer, parameter dp = real64
real(dp), parameter pi = 3.141592653589793238_dp
real(dp), parameter electronvolt = 27.211386245988_dp
integer, parameter slater_1s_code = 100
integer, parameter sto_3g_code = 200
Variable Documentation
dp
integer, parameter shared_constants::dp = real64
Definition at line 5 of file constants.f90.
   integer, parameter :: dp = real64
Referenced by main_driver().
electronvolt
real(dp), parameter shared_constants::electronvolt = 27.211386245988_dp
Definition at line 7 of file constants.f90.
   real(dp),parameter :: electronvolt = 27.211386245988_dp
Referenced by main_driver().
pi
real(dp), parameter shared_constants::pi = 3.141592653589793238_dp
Definition at line 6 of file constants.f90.
   real(dp),parameter :: pi = 3.141592653589793238_dp
Referenced by component_functions::centered_gaussian(), and component_functions::centered_slater_1s().
slater_1s_code
integer, parameter shared_constants::slater_1s_code = 100
Definition at line 10 of file constants.f90.
   integer, parameter :: slater_1s_code = 100
Referenced by basis_functions::initialise_basis(), and main_driver().
sto_3g_code
integer, parameter shared_constants::sto_3g_code = 200
Definition at line 11 of file constants.f90.
   integer, parameter :: sto_3g_code = 200
Referenced by basis_functions::initialise_basis().