PX 915: Variational Quantum Monte Carlo - LATIN: write_file Module Reference
write_file Module Reference
Contains all the subroutines related to writing results to file.
Functions/Subroutines
subroutine result_netcdf (dof, ele, num_ele, num_nuc)
Main results writing to NetCDF file.
subroutine energies_netcdf (energies, bondlen)
Output results for bond lengths and corresponding energy used for plotting.
subroutine xy_grid (points, box_size)
Writes the xyz coordinates used in the calculation of either the wavefunction or electron density to a text file names xyz.txt.
subroutine write_restart_file (gp_n_data, gp_n_dof, n_cycles, no_samples, current_best_E, constant_mean_value, gamma, kernel_var, kernal_inv_length, E_data, data_mean, param_pres, param_cov, param_data)
Creates a NetCDF file which contains information needed for the restart of the Bi_Op_step function.
subroutine handle_err (ierr)
Handles the NetCDF errors and print statements.
Detailed Description
Contains all the subroutines related to writing results to file.
This module contains all the subroutines needed for all the output result files which will be used for plotting and restarting.
Function/Subroutine Documentation
energies_netcdf()
subroutine write_file::energies_netcdf (real(dp), dimension(:), intent(in) energies, real(dp), dimension(:), intent(in) bondlen)
Output results for bond lengths and corresponding energy used for plotting.
Will only be used for the 2 nuclei case.
Parameters
filename outputs a NetCDF file named bond_length.nc4
Dimension names
ID's
Inputting the data
Writing data to file
Closing the file
Definition at line 115 of file netcdf_file.f90.
     INTEGER, PARAMETER :: dp=kind(1.0d0)
     ! Inputting variables
     CHARACTER(LEN=100) :: filename = 'bond_length.nc4'
     REAL(dp), DIMENSION(:), INTENT(IN) :: energies, bondlen
     CHARACTER(LEN=100), DIMENSION(1) :: dim_e = (/"Energy"/)
     CHARACTER(LEN=100), DIMENSION(1) :: dim_b = (/"Bond_Lengths"/)
     ! File IDs
     INTEGER :: ierr, file_id
     ! Variable ID's
     INTEGER :: var_e, var_b
     ! Dimension ID's for the arrays
     INTEGER, DIMENSION(1) :: did_e, did_b
     ! Implicit types for the array sizes
     INTEGER, DIMENSION(1) :: size_e, size_b
     ! Create the file
     ierr = nf90_create(filename, nf90_clobber, file_id)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ! Variable sizes
     size_e = shape(energies)
     size_b = shape(bondlen)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ! Energies
     ierr = nf90_def_dim(file_id, dim_e(1), size_e(1), did_e(1))
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_def_var(file_id, "Energy", nf90_double, did_e, var_e)
     ! Bond length
     ierr = nf90_def_dim(file_id, dim_b(1), size_b(1), did_b(1))
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_def_var(file_id, "Bond_length", nf90_double, did_b, var_b)
       ! Metadata
     ierr = nf90_enddef(file_id)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ! Energy
     ierr = nf90_put_var(file_id, var_e, energies)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_put_var(file_id, var_b, bondlen)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_close(file_id)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     !Finishing statement if writing file is successful.
     print *, "Success in writing the NETCDF file: ", filename
References handle_err().
handle_err()
subroutine write_file::handle_err (integer, intent(in) ierr)
Handles the NetCDF errors and print statements.
This subroutine is only used and called within this module.
Definition at line 436 of file netcdf_file.f90.
     INTEGER, INTENT(IN) :: ierr
     IF (ierr /= nf90_noerr) THEN
       print *, trim(nf90_strerror(ierr))
       ! Stops the code if an error is found
       stop "Stopped"
     END IF
Referenced by energies_netcdf(), result_netcdf(), and write_restart_file().
result_netcdf()
subroutine write_file::result_netcdf (real(dp), dimension(:), intent(in) dof, real(dp), dimension(:), intent(in) ele, integer, intent(in) num_ele, integer, intent(in) num_nuc)
Main results writing to NetCDF file.
The result_netcdf subroutine outputs the main NetCDF result file containing the optimal degrees of freedom, either the electron density or wavefunction and the number of electrons and nuclei used. Saves the file as results.nc4 which is used Has error statements printed out at each section in order to aid with debugging.
Parameters
[in] dof dof the optimal degrees of freedom
[in] ele ele an rank 1 array containing either the wavefunction or electron density results evaluated on a grid op coordinates (for 1 or 2 electron system respectively).
[in] num_ele num_ele the number of electrons used in the calculation
num_nuc the number of nuclei used in the calculation
[in] num_nuc num_ele the number of electrons used in the calculation
num_nuc the number of nuclei used in the calculation
Dimension names for the arrays.
ID's
Inputting the data
Writing the data to file
Closing the file
Definition at line 19 of file netcdf_file.f90.
     INTEGER, PARAMETER :: dp=kind(1.0d0)
     CHARACTER(LEN=100) :: filename = 'results.nc4'
     REAL(dp), DIMENSION(:), INTENT(IN) :: dof
     REAL(dp), DIMENSION(:), INTENT(IN) :: ele
     INTEGER, INTENT(IN) :: num_ele, num_nuc
     CHARACTER(LEN=100), DIMENSION(1) :: dim_dof = (/"Optimal_DOF"/)
     CHARACTER(LEN=100), DIMENSION(1) :: dim_ele = (/"Electron_Density"/)
     ! File ID's
     INTEGER :: ierr, file_id
     ! Variable ID's
     INTEGER :: var_dof,  var_ele, var_num_ele, var_num_nuc
     ! Dimension ID's for the arrays
     INTEGER, DIMENSION(1) :: did_dof, did_ele
     ! Implicit types for the sizes for the arrays
     INTEGER, DIMENSION(1) :: size_dof, size_ele
     ! Create the file
     ierr = nf90_create(filename, nf90_clobber, file_id)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ! Variable sizes
     size_dof = shape(dof)
     size_ele = shape(ele)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ! Number of electrons
     ierr = nf90_def_var(file_id, "Num_of_Electrons", nf90_double, var_num_ele)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ! Number of nuclei
     ierr = nf90_def_var(file_id, "Num_of_Nuclei", nf90_double, var_num_nuc)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ! DOF
     ierr = nf90_def_dim(file_id, dim_dof(1), size_dof(1), did_dof(1))
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_def_var(file_id, "Optimal_DOF", nf90_double, did_dof, var_dof)
     ! Electron Density
     ierr = nf90_def_dim(file_id, dim_ele(1), size_ele(1), did_ele(1))
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_def_var(file_id, "Electron_Density", nf90_double, did_ele, var_ele)
     ! Metadata
     ierr = nf90_enddef(file_id)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ! Number of electrons
     ierr = nf90_put_var(file_id, var_num_ele, num_ele)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ! Number of nuclei
     ierr = nf90_put_var(file_id, var_num_nuc, num_nuc)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ! DOF
     ierr = nf90_put_var(file_id, var_dof, dof)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ! Electron Density
     ierr = nf90_put_var(file_id, var_ele, ele)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_close(file_id)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     !Finishing statement if writing file is successful.
     print *, "Success in writing the NETCDF file: ", filename
References handle_err().
Referenced by main_driver().
write_restart_file()
subroutine write_file::write_restart_file (real(dp) gp_n_data, real(dp) gp_n_dof, real(dp) n_cycles, real(dp) no_samples, real(dp) current_best_E, real(dp) constant_mean_value, real(dp) gamma, real(dp) kernel_var, real(dp) kernal_inv_length, real(dp), dimension(:), intent(in) E_data, real(dp), dimension(:), intent(in) data_mean, real(dp), dimension(:,:), intent(in) param_pres, real(dp), dimension(:,:), intent(in) param_cov, real(dp), dimension(:,:), intent(in) param_data)
Creates a NetCDF file which contains information needed for the restart of the Bi_Op_step function.
This file will be created in the event that the Bi_Op_step function crashes.
Parameters
gp_n_data Defining everything for the scalar variables
gp_n_data is the data used for the GP surrogate
gp_n_dof is the degrees of freedom used for the GP surrogate
n_cycles is the number of cycles
no_samples is the number of samples
current_best_E is the current best energy found so far during the run.
constant_mean_value
gamma
kernel_var
kernal_inv_length
gp_n_dof Defining everything for the scalar variables
gp_n_data is the data used for the GP surrogate
gp_n_dof is the degrees of freedom used for the GP surrogate
n_cycles is the number of cycles
no_samples is the number of samples
current_best_E is the current best energy found so far during the run.
constant_mean_value
gamma
kernel_var
kernal_inv_length
n_cycles Defining everything for the scalar variables
gp_n_data is the data used for the GP surrogate
gp_n_dof is the degrees of freedom used for the GP surrogate
n_cycles is the number of cycles
no_samples is the number of samples
current_best_E is the current best energy found so far during the run.
constant_mean_value
gamma
kernel_var
kernal_inv_length
no_samples Defining everything for the scalar variables
gp_n_data is the data used for the GP surrogate
gp_n_dof is the degrees of freedom used for the GP surrogate
n_cycles is the number of cycles
no_samples is the number of samples
current_best_E is the current best energy found so far during the run.
constant_mean_value
gamma
kernel_var
kernal_inv_length
current_best_e Defining everything for the scalar variables
gp_n_data is the data used for the GP surrogate
gp_n_dof is the degrees of freedom used for the GP surrogate
n_cycles is the number of cycles
no_samples is the number of samples
current_best_E is the current best energy found so far during the run.
constant_mean_value
gamma
kernel_var
kernal_inv_length
[in] e_data Defining everything for the array variables Rank 1 arrays
E_data is a rank 1 array containing the energy data
data_mean is the
[in] param_pres Rank 2 arrays
param_pres rank 2 array containing @param_cov rank 2 array containing the covariance matrix
param_data
Dimension Names - named the same as the input variables
ID's
Create the file
Defining the Scalar Variables
Inputting in the Array variables and defining the dimensions
Rank 1 arrays first
Rank 2 arrays
Writing the array data to file
Scalar Values
Rank 1 arrays
Rank 2 arrays
Closing the file
Definition at line 224 of file netcdf_file.f90.
     INTEGER, PARAMETER :: dp=kind(1.0d0)
     ! Declaring the input variables
     CHARACTER(LEN=100) :: filename = 'restart.nc4'
     INTEGER :: ierr, file_id, i
     REAL(dp) :: gp_n_data, gp_n_dof, n_cycles, no_samples, current_best_E
     REAL(dp) :: constant_mean_value, gamma, kernel_var, kernal_inv_length
     INTEGER :: var_gp_n_data, var_gp_n_dof, var_n_cycles, var_no_samples
     INTEGER :: var_current_best_E, var_constant_mean_value, var_gamma
     INTEGER :: var_kernel_var, var_kernal_inv_length
     REAL(dp), DIMENSION(:), INTENT(IN) :: E_data
     REAL(dp), DIMENSION(:), INTENT(IN) :: data_mean
     REAL(dp), DIMENSION(:,:), INTENT(IN) :: param_pres
     REAL(dp), DIMENSION(:,:), INTENT(IN) :: param_cov
     REAL(dp), DIMENSION(:,:), INTENT(IN) :: param_data
     CHARACTER(LEN=100), DIMENSION(1) :: dim_e_data = (/"E_Data"/)
     CHARACTER(LEN=100), DIMENSION(1) :: dim_data_mean = (/"data_mean"/)
     CHARACTER(LEN=100), DIMENSION(2) :: dim_param_pres = (/"param_pres","param_pres"/)
     CHARACTER(LEN=100), DIMENSION(2) :: dim_param_cov = (/"param_cov","param_cov"/)
     CHARACTER(LEN=100), DIMENSION(2) :: dim_param_data = (/"param_data","param_data"/)
     ! Variable IDs
     INTEGER :: var_e_data, var_data_mean, var_param_pres
     INTEGER :: var_param_cov, var_param_data
     ! Dimension IDs for the arrays
     INTEGER, DIMENSION(1) :: did_e_data, did_data_mean
     INTEGER, DIMENSION(2) :: did_param_cov, did_param_data, did_param_pres
     ! Sizes for the arrays
     INTEGER, DIMENSION(1) :: size_e_data, size_data_mean
     INTEGER, DIMENSION(2) :: size_param_cov, size_param_data, size_param_pres
     ierr = nf90_create(filename, nf90_clobber, file_id)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ! Variable sizes
     size_e_data = shape(e_data)
     size_data_mean = shape(data_mean)
     size_param_pres = shape(param_pres)
     size_param_cov = shape(param_cov)
     size_param_data = shape(param_data)
     ierr = nf90_def_var(file_id, "gp_n_data", nf90_double, var_gp_n_data)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_def_var(file_id, "gp_n_dof", nf90_double, var_gp_n_dof)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_def_var(file_id, "n_cycles", nf90_double, var_n_cycles)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_def_var(file_id, "no_samples", nf90_double, var_no_samples)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_def_var(file_id, "current_best_e", nf90_double, var_current_best_e)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_def_var(file_id, "constant_mean_value", nf90_double, var_constant_mean_value)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_def_var(file_id, "gamma", nf90_double, var_gamma)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_def_var(file_id, "kernel_var", nf90_double, var_kernel_var)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_def_var(file_id, "kernal_inv_length", nf90_double, var_kernal_inv_length)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_def_dim(file_id, dim_e_data(1), size_e_data(1), did_e_data(1))
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_def_var(file_id, "E_data", nf90_double, did_e_data, var_e_data)
     ierr = nf90_def_dim(file_id, dim_data_mean(1), size_data_mean(1), did_data_mean(1))
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_def_var(file_id, "data_mean", nf90_double, did_data_mean, var_data_mean)
     DO i = 1,2
       ierr = nf90_def_var(file_id, dim_param_pres(i), size_param_pres(i), did_param_pres(i))
       IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     END DO
     ierr = nf90_def_var(file_id, "param_pres", nf90_double, did_param_pres, var_param_pres)
     DO i = 1,2
       ierr = nf90_def_var(file_id, dim_param_cov(i), size_param_cov(i), did_param_cov(i))
       IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     END DO
     ierr = nf90_def_var(file_id, "param_cov", nf90_double, did_param_cov, var_param_cov)
     DO i = 1,2
       ierr = nf90_def_var(file_id, dim_param_data(i), size_param_data(i), did_param_data(i))
       IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     END DO
     ierr = nf90_def_var(file_id, "param_data", nf90_double, did_param_data, var_param_data)
     ! Metadata
     ierr = nf90_enddef(file_id)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_put_var(file_id, var_gp_n_data, gp_n_data)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_put_var(file_id, var_gp_n_dof, gp_n_dof)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_put_var(file_id, var_n_cycles, n_cycles)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_put_var(file_id, var_no_samples, no_samples)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_put_var(file_id, var_current_best_e, current_best_e)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_put_var(file_id, var_constant_mean_value, constant_mean_value)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_put_var(file_id, var_gamma, gamma)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_put_var(file_id, var_kernel_var, kernel_var)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_put_var(file_id, var_kernal_inv_length, kernal_inv_length)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_put_var(file_id, var_e_data, e_data)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_put_var(file_id, var_data_mean, data_mean)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_put_var(file_id, var_param_pres, param_pres)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_put_var(file_id, var_param_cov, param_cov)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_put_var(file_id, var_param_data, param_data)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     ierr = nf90_close(file_id)
     IF (ierr /= nf90_noerr) CALL handle_err(ierr)
     print *, "Success in writing file: ", filename
References handle_err().
xy_grid()
subroutine write_file::xy_grid (integer, intent(in) points, real(dp), intent(in) box_size)
Writes the xyz coordinates used in the calculation of either the wavefunction or electron density to a text file names xyz.txt.
This only produces a equally spaced square grid of points in the x-y plane, with the z coordinate being set to zero. These coordinates are used for the 2D contour plot in the resulting output plot.
Parameters
[in] box_size box_size is the user defined parameter which defines the size of the domain in each axis.
[in] points points is the user defined
Definition at line 185 of file netcdf_file.f90.
     INTEGER, PARAMETER :: dp=kind(1.0d0)
     REAL(dp), INTENT(IN) :: box_size
     INTEGER, INTENT(IN) :: points
     ! Loop variables
     INTEGER :: i,j
     ! Resulting position values in x-y axis
     REAL(dp) :: a, b ! a is x, b is y
     INTEGER, PARAMETER :: file_no=3
     ! Opens an empty text file
     OPEN (unit=file_no,file="xyz.txt",action="write")
     DO i = -points, points
       DO j = -points, points
         ! Scales the positions to be between -box_size and +box_size
         a =  (real(i) / (abs(points) + abs(points)))*box_size
         b =  (real(j) / (abs(points) + abs(points)))*box_size
         ! Writes the coordinates to file, the z coordinate is set to zero as only using this for 2D contour plot which requires x and y coordinates to change.
         write (file_no,*) a,b,0
       END DO
     END DO
     ! Closes the file after writing
     CLOSE (file_no)
     print*, 'Success in writing: xyz.txt'
Referenced by main_driver().