PX 915: Variational Quantum Monte Carlo - LATIN: gradient_estimator Module Reference
gradient_estimator Module Reference
Subroutines for obtaining a gradient estimation through Cholesky decomposition.
Functions/Subroutines
subroutine get_cholesky (cholesky_decomp, matrix_in)
performs Cholesky decomposition without destroying the old array.
real(dp) function, dimension(:), allocatable m_vector (x, previous_best)
builds the "m_vector" as described in: arXiv:1602.05149v4 [stat.ML] 5 May 2019 contains the difference between the mean and best result in a vector.
real(dp) function, dimension(:), allocatable z_vector (z_in)
build the "z_vector" as described in: arXiv:1602.05149v4 [stat.ML] 5 May 2019
integer function, dimension(1) find_max_thread (m_vec, z_vec, c_mat)
finds the location in the vector that corresponds to the maximum of "m + CZ"
subroutine check_max_is_unique (m_vec, z_vec, c_mat, find_max_thread)
check if the maximum found in the find_max_thread is a unique value.
subroutine init_diff_f (x, z_in, previous_best)
initialises the workspace F and Cholesky decomposition of the covariance matrix.
subroutine bkwd_diff_f ()
performs the backward difference differentiation on the workspace F
subroutine combine_f_grad_k (x, n_params)
combines the gradient contributions from the workspace F and those associated with the m_vector and covariance matrix.
real(dp) function, dimension(:,:), allocatable run_gradient_estimator (x, z_in, n_params, previous_best)
runs the gradient estimator associated routines from one block.
Variables
real(dp), dimension(:,:), allocatable f_ij
real(dp), dimension(:,:), allocatable l_ij
real(dp), dimension(:,:), allocatable gradient_matrix
real(dp) check_max
Detailed Description
Subroutines for obtaining a gradient estimation through Cholesky decomposition.
Function/Subroutine Documentation
bkwd_diff_f()
subroutine gradient_estimator::bkwd_diff_f
performs the backward difference differentiation on the workspace F
Definition at line 158 of file gradient_estimator.f90.
   integer :: i, j, k, N
   integer, dimension(2) :: shape_arr
   shape_arr = shape(f_ij)
   n = shape_arr(1)
   do k=n,1, -1
     if (abs(l_ij(k,k)) > 0.0_dp) then
     !row operations
     do j = k+1, n
       do i = j, n
         f_ij(i,k) = f_ij(i,k) - f_ij(i,j)*l_ij(j,k)
         f_ij(j,k) = f_ij(j,k) - f_ij(i,j)*l_ij(i,k)
       end do
     end do
     !lead column
     do j = k+1, n
       f_ij(j,k) = f_ij(j,k)/l_ij(k,k)
       f_ij(k,k) = f_ij(k,k) - l_ij(j,k)* f_ij(j,k)
     end do
     !pivot
     f_ij(k,k) = 0.5_dp*f_ij(k,k)/l_ij(k,k)
     end if
   end do
References f_ij, and l_ij.
Referenced by run_gradient_estimator().
check_max_is_unique()
subroutine gradient_estimator::check_max_is_unique (real(dp), dimension(:), intent(in) m_vec, real(dp), dimension(:), intent(in) z_vec, real(dp), dimension(:,:), intent(in) c_mat, integer, dimension(1), intent(in) find_max_thread)
check if the maximum found in the find_max_thread is a unique value.
Parameters
m_vec as returned from the m_vector function.
z_vec as returned from the z_vector function.
c_mat corresponds to the Cholesky decomposition of the covariance matrix.
find_max_thread integer containing the location of the maximum of "m + CZ"
Definition at line 87 of file gradient_estimator.f90.
     integer, dimension(1), intent(in) :: find_max_thread
     real(dp), dimension(:,:) , intent(in):: c_mat
     real(dp), dimension(:), intent(in) :: m_vec, z_vec
     real(dp), dimension(:), allocatable :: f_vector
     integer :: i
     !make sure indexing starts from 0, so is consistent.
     allocate(f_vector(0:( size(z_vec) -1 )))
     !by default set = 1, so it does nothing when multiplied with something.
     check_max = 1.0_dp
     f_vector = m_vec + matmul(c_mat, z_vec)
     !loop over each element of the calculated vector and check if it equals the max of that vector
     !but in more than one location.
     do i = 0, size(f_vector) -1
       if ( (f_vector(i) .EQ. f_vector(find_max_thread(1))) .AND. (i .NE. find_max_thread(1)) ) then
         check_max=0.0_dp
       end if
     end do
     deallocate(f_vector)
References check_max.
Referenced by init_diff_f().
combine_f_grad_k()
subroutine gradient_estimator::combine_f_grad_k (real(dp), dimension(:,:) x, integer n_params)
combines the gradient contributions from the workspace F and those associated with the m_vector and covariance matrix.
Parameters
x is 2D array containing the param_inputs for each thread.
n_params is the total number of parameters being evaluated
Definition at line 189 of file gradient_estimator.f90.
   real(dp), dimension(:,:) :: x
   real(dp), dimension(:,:), allocatable :: grad_mu
   real(dp), dimension(:,:,:,:), allocatable:: post_grad_in
   integer, dimension(2) :: shape_arr
   integer, dimension(4) :: shape_arr_4
   integer :: i, j, k, l, n_params
   shape_arr = shape(x)
   if allocated(post_grad_in) then
     deallocate(post_grad_in)
   end if
   allocate(post_grad_in(shape_arr(1), shape_arr(1), shape_arr(1), n_params))
   if allocated(grad_mu) then
     deallocate(grad_mu)
   end if
   allocate(grad_mu( shape_arr(1), n_params ))
   call gp_post_k_grad(x, shape_arr(1), post_grad_in)
   shape_arr_4 = shape(post_grad_in)
   !print*, shape_arr_4(:)
   if allocated(gradient_matrix) then
     deallocate(gradient_matrix)
   end if
   allocate(gradient_matrix(shape_arr_4(3), shape_arr_4(4))  )
   gradient_matrix = 0.0_dp
   do k = 1, shape_arr_4(3)
     do l = 1, shape_arr_4(4)
       do i = 1, shape_arr_4(1)
         do j = 1, shape_arr_4(2)
           gradient_matrix(k,l) = gradient_matrix(k,l) + f_ij(i,j)*post_grad_in(i,j,k,l)
         end do
       end do
     end do
   end do
   !gradient in param space associated with each mean.
   grad_mu = gp_mu_post_grad(x,shape_arr(1))
   gradient_matrix = (gradient_matrix - grad_mu)
   !deallocate(F_ij, L_ij)
References f_ij, gp_surrogate::gp_mu_post_grad(), gp_surrogate::gp_post_k_grad(), and gradient_matrix.
Referenced by run_gradient_estimator().
find_max_thread()
integer function, dimension(1) gradient_estimator::find_max_thread (real(dp), dimension(:), intent(in) m_vec, real(dp), dimension(:), intent(in) z_vec, real(dp), dimension(:,:), intent(in) c_mat)
finds the location in the vector that corresponds to the maximum of "m + CZ"
Parameters
m_vec as returned from the m_vector function.
z_vec as returned from the z_vector function.
c_mat corresponds to the Cholesky decomposition of the covariance matrix.
Definition at line 70 of file gradient_estimator.f90.
     real(dp), dimension(:,:) , intent(in):: c_mat
     real(dp), dimension(:), intent(in) :: m_vec, z_vec
     integer, dimension(1) :: find_max_thread
     integer, dimension(2) :: shape_arr
     shape_arr = shape(c_mat)
     find_max_thread = maxloc(m_vec + matmul(c_mat, z_vec)) - 1
     !-1 is shift the indexing back to 0 from 1.
Referenced by init_diff_f().
get_cholesky()
subroutine gradient_estimator::get_cholesky (real(dp), dimension(:,:) cholesky_decomp, real(dp), dimension(:,:) matrix_in)
performs Cholesky decomposition without destroying the old array.
also with 0 at i=0 padding.
Parameters
cholesky_decomp is where the result is stored.
matrix_in 2D matrix to be decomposed.
Definition at line 20 of file gradient_estimator.f90.
   real(dp), dimension(:,:) :: matrix_in, cholesky_decomp
   real(dp), dimension(:,:), allocatable :: get_cholesky_temp
   integer :: info
   integer, dimension(2) :: shape_arr
   get_cholesky_temp = matrix_in
   shape_arr = shape(matrix_in)
   call dpotrf( 'L', shape_arr(1), get_cholesky_temp, shape_arr(1),info) !this is the LAPACK routine for getting Cholesky 'L' = lower triangle. info has an error state
   cholesky_decomp = 0.0_dp
   cholesky_decomp(1:shape_arr(1), 1:shape_arr(1)) = -get_cholesky_temp
Referenced by init_diff_f().
init_diff_f()
subroutine gradient_estimator::init_diff_f (real(dp), dimension(:,:), intent(in) x, real(dp), dimension(:), intent(in) z_in, real(dp), intent(in) previous_best)
initialises the workspace F and Cholesky decomposition of the covariance matrix.
Parameters
x is 2D array containing the param_inputs for each thread.
z_in is a 1D array of normally distributed numbers.
previous_best is a real number containing the best energy from the prior trial.
Definition at line 113 of file gradient_estimator.f90.
   real(dp), dimension(:,:) , intent(in):: x
   real(dp), intent(in) :: previous_best
   real(dp), dimension(:), intent(in) :: z_in
   real(dp), dimension(:), allocatable :: m_vec, z_vec
   real(dp), dimension(:,:), allocatable :: c_mat, init_F_ij
   integer, dimension(2) :: shape_arr
   integer, dimension(1) :: loc_max_thread
   integer :: i, j
   shape_arr = shape(x)
   allocate(m_vec(0:shape_arr(1)))
   allocate(z_vec(0:shape_arr(1)))
   allocate(c_mat(0:shape_arr(1), 0:shape_arr(1)  ))
   allocate(init_f_ij(0:shape_arr(1), 0:shape_arr(1)))
   if (allocated(f_ij)) then
     deallocate(f_ij)
   end if
   allocate(f_ij(1:shape_arr(1), 1:shape_arr(1)))
   if (allocated(l_ij)) then
     deallocate(l_ij)
   end if
   allocate(l_ij(1:shape_arr(1), 1:shape_arr(1)))
   init_f_ij = 0.0_dp
   m_vec = m_vector(x, previous_best)
   z_vec = z_vector(z_in)
   call get_cholesky(c_mat, gp_k_post(x, shape_arr(1))  )
   loc_max_thread = find_max_thread(m_vec, z_vec, c_mat)
   !print*, loc_max_thread
   !This is the analytical result of diffing the max(f) w.r.t each L(ij)
   init_f_ij( loc_max_thread(1) , 1:loc_max_thread(1)  ) = -z_vec(1:loc_max_thread(1))
   !putting array back into correct size (removing index 0, padding)
   f_ij =   init_f_ij(1:shape_arr(1) , 1:shape_arr(1))
   !put cholesky in same size array, removing 0 index padding.
   l_ij = c_mat(1:shape_arr(1) , 1:shape_arr(1))
   call check_max_is_unique(m_vec, z_vec, c_mat, loc_max_thread)
   deallocate(c_mat, z_vec, m_vec, init_f_ij)
References check_max_is_unique(), f_ij, find_max_thread(), get_cholesky(), l_ij, m_vector(), and z_vector().
Referenced by run_gradient_estimator().
m_vector()
real(dp) function, dimension(:), allocatable gradient_estimator::m_vector (real(dp), dimension(:,:), intent(in) x, real(dp), intent(in) previous_best)
builds the "m_vector" as described in: arXiv:1602.05149v4 [stat.ML] 5 May 2019 contains the difference between the mean and best result in a vector.
Parameters
x is 2D array containing the param_inputs for each thread.
previous_best is a real number containing the best energy from the prior trial.
Definition at line 38 of file gradient_estimator.f90.
   real(dp), dimension(:), allocatable :: m_vector, pbest_arr
   real(dp), dimension(:,:) , intent(in):: x
   real(dp), intent(in) :: previous_best
   integer, dimension(2) :: shape_arr
   shape_arr = shape(x)
   allocate(m_vector(0:shape_arr(1)))
   allocate(pbest_arr(shape_arr(1)))
   pbest_arr = previous_best !need an array to compare each thread/trial/point in param space.
   m_vector(0) = 0.0_dp
   m_vector(1:shape_arr(1))=pbest_arr - gp_mu_post(x, shape_arr(1))
References gp_surrogate::gp_mu_post().
Referenced by init_diff_f().
run_gradient_estimator()
real(dp) function, dimension(:,:), allocatable gradient_estimator::run_gradient_estimator (real(dp), dimension(:,:), intent(in) x, real(dp), dimension(:), intent(in) z_in, integer, intent(in) n_params, real(dp), intent(in) previous_best)
runs the gradient estimator associated routines from one block.
Parameters
x is 2D array containing the param_inputs for each thread.
n_params is the total number of parameters being evaluated.
z_in is a 1D array of normally distributed numbers.
previous_best is a real number containing the best energy from the prior trial.
Definition at line 241 of file gradient_estimator.f90.
     real(dp), dimension(:,:), intent(in) :: x
     real(dp), dimension(:,:), allocatable :: run_gradient_estimator
     real(dp), dimension(:), intent(in) :: z_in
     integer, intent(in) :: n_params
     real(dp), intent(in) :: previous_best
     call init_diff_f(x,z_in, previous_best)
     call bkwd_diff_f()
     call combine_f_grad_k(x, n_params)
     if allocated(run_gradient_estimator) then
       deallocate(run_gradient_estimator)
     end if
     allocate(run_gradient_estimator, mold=gradient_matrix)
     run_gradient_estimator = gradient_matrix*check_max
     !deallocate(gradient_matrix)
References bkwd_diff_f(), check_max, combine_f_grad_k(), gradient_matrix, and init_diff_f().
Referenced by stoch_grad::g_t().
z_vector()
real(dp) function, dimension(:), allocatable gradient_estimator::z_vector (real(dp), dimension(:), intent(in) z_in)
build the "z_vector" as described in: arXiv:1602.05149v4 [stat.ML] 5 May 2019
Parameters
z_in is a 1D array of normally distributed numbers.
Definition at line 55 of file gradient_estimator.f90.
   real(dp), dimension(:), allocatable :: z_vector
   real(dp), dimension(:), intent(in) :: z_in
   integer :: size_z
   size_z = size(z_in)
   allocate(z_vector(0:size_z))
   z_vector(0) = 0
   z_vector(1:size_z) = z_in
Referenced by init_diff_f().
Variable Documentation
check_max
real(dp) gradient_estimator::check_max
Definition at line 13 of file gradient_estimator.f90.
   real(dp) :: check_max
Referenced by check_max_is_unique(), and run_gradient_estimator().
f_ij
real(dp), dimension(:,:), allocatable gradient_estimator::f_ij
Definition at line 12 of file gradient_estimator.f90.
   real(dp), dimension(:,:), allocatable :: F_ij, L_ij, gradient_matrix
Referenced by bkwd_diff_f(), combine_f_grad_k(), and init_diff_f().
gradient_matrix
real(dp), dimension(:,:), allocatable gradient_estimator::gradient_matrix
Definition at line 12 of file gradient_estimator.f90.
Referenced by combine_f_grad_k(), and run_gradient_estimator().
l_ij
real(dp), dimension(:,:), allocatable gradient_estimator::l_ij
Definition at line 12 of file gradient_estimator.f90.
Referenced by bkwd_diff_f(), and init_diff_f().