PX 915 Project Title/Name Here: component_functions Module Reference
component_functions Module Reference
Basic subfunctions This module contains basic functions used in basis_functions.f90.
Functions/Subroutines
real(dp) function centered_gaussian (position, alpha)
Gaussian distribution centred at the origin.
real(dp) function centered_gaussian_laplacian (position, alpha)
Analytic Laplacian of Gaussian distribution centred at the origin.
real(dp) function centered_slater_1s (position, zeta)
Slater-1s distribution centred at the origin.
real(dp) function centered_slater_1s_laplacian (position, zeta)
Analytic Laplacian of Slater-1s distribution centred at the origin.
real(dp) function correlation_range (r, d)
Functions that construct the Jastrow interaction function Notation here follows Schmidt and Moskowitz 1990, refered to as SM90.
real(dp) function correlation_subterm (r_12, r_I1, r_I2, m, n, o)
Jastrow subfuction: basic subterm Subterm of the correlation function, one for each Jastrow dof per atom This is the term in the k sum in Schmidt and Moskowitz 1990.
real(dp) function correlation_atom_term (atom_coord, electron_coords, mno_parameters, c, b, d)
Jastrow subfuction: atom subterm Correlation term for each atom.
real(dp) function correlation_function (atom_coords, electron_coords, mno_parameters, c, b, d)
Jastrow correlation fuction Function F from Schmidt and Moskowitz 1990.
Detailed Description
Basic subfunctions This module contains basic functions used in basis_functions.f90.
Function/Subroutine Documentation
centered_gaussian()
real(dp) function component_functions::centered_gaussian (real(dp), dimension(3), intent(in) position, real(dp), intent(in) alpha)
Gaussian distribution centred at the origin.
Parameters
[in] position Space Coordinate
[in] alpha Length scale
Definition at line 11 of file component_functions.f90.
     implicit none
     real(dp) :: centered_gaussian
     real(dp), dimension(3), intent(in) :: position
     real(dp), intent(in) :: alpha
     centered_gaussian = (2.0_dp * alpha /pi)**(0.75_dp)*exp(-alpha * dot_product(position,position))
References shared_constants::pi.
Referenced by centered_gaussian_laplacian(), and basis_functions::wave_function_sto3g().
centered_gaussian_laplacian()
real(dp) function component_functions::centered_gaussian_laplacian (real(dp), dimension(3), intent(in) position, real(dp), intent(in) alpha)
Analytic Laplacian of Gaussian distribution centred at the origin.
Parameters
[in] position Space Coordinate
[in] alpha Length scale
Definition at line 22 of file component_functions.f90.
     implicit none
     real(dp) :: centered_gaussian_laplacian
     real(dp), dimension(3), intent(in) :: position
     real(dp), intent(in) :: alpha
     centered_gaussian_laplacian = &
     (-6.0_dp*alpha + 4.0_dp*alpha**2*dot_product(position,position))*centered_gaussian(position,alpha)
References centered_gaussian().
Referenced by basis_functions::reduced_hamiltonian_sto3g().
centered_slater_1s()
real(dp) function component_functions::centered_slater_1s (real(dp), dimension(3), intent(in) position, real(dp), intent(in) zeta)
Slater-1s distribution centred at the origin.
Parameters
[in] position Space Coordinate
[in] zeta Length scale
Definition at line 35 of file component_functions.f90.
     implicit none
     real(dp) :: centered_slater_1s
     real(dp), dimension(3), intent(in) :: position
     real(dp),intent(in) :: zeta
     centered_slater_1s = ( zeta**3 /pi)**(0.5_dp)*exp(-zeta * norm2(position))
References shared_constants::pi.
Referenced by centered_slater_1s_laplacian(), and basis_functions::wave_function_slater_1s().
centered_slater_1s_laplacian()
real(dp) function component_functions::centered_slater_1s_laplacian (real(dp), dimension(3), intent(in) position, real(dp), intent(in) zeta)
Analytic Laplacian of Slater-1s distribution centred at the origin.
Parameters
[in] position Space Coordinate
[in] zeta Length scale
Definition at line 47 of file component_functions.f90.
     implicit none
     real(dp) :: centered_slater_1s_laplacian
     real(dp), dimension(3), intent(in) :: position
     real(dp), intent(in) :: zeta
     centered_slater_1s_laplacian = &
     (-2.0_dp*zeta/norm2(position) + zeta**2)*centered_slater_1s(position,zeta)
References centered_slater_1s().
Referenced by basis_functions::reduced_hamiltonian_slater_1s().
correlation_atom_term()
real(dp) function component_functions::correlation_atom_term (real(dp), dimension(3), intent(in) atom_coord, real(dp), dimension(6), intent(in) electron_coords, integer, dimension(:,:), intent(in) mno_parameters, real(dp), dimension(:), intent(in) c, real(dp), intent(in) b, real(dp), intent(in) d)
Jastrow subfuction: atom subterm Correlation term for each atom.
U_I12 from Schmidt and Moskowitz 1990
Parameters
[in] atom_coord Space coordinates of atom
[in] electron_coords Space positions of electrons
[in] mno_parameters Jastrow interger parameters
[in] c Jastrow dofs
[in] b Inverse lengthscale of nuclear-electron interaction
[in] d Inverse lengthscale of electron-electron interaction
Definition at line 105 of file component_functions.f90.
     implicit none
     real(dp) :: correlation_atom_term
     real(dp), dimension(3), intent(in) :: atom_coord
     real(dp), dimension(6), intent(in) :: electron_coords
     integer, dimension(:,:), intent(in) :: mno_parameters
     real(dp), dimension(:), intent(in) :: c
     real(dp), intent(in) :: b
     real(dp), intent(in) :: d
     ! Internal variables
     real(dp) :: r_12 ! Distance between electrons
     real(dp) :: r_I1 ! Distance from atom to electron 1
     real(dp) :: r_I2 ! Distance from atom to electron 2
     integer :: k ! Loop variable
     ! Compute distances
     r_12 = correlation_range(norm2(electron_coords(1:3)-electron_coords(4:6)),d)
     r_i1 = correlation_range(norm2(atom_coord-electron_coords(1:3)),b)
     r_i2 = correlation_range(norm2(atom_coord-electron_coords(4:6)),b)
     ! k sum from Schmidt and Moskowitz 1990 to compute U_I12
     correlation_atom_term = 0.0_dp
     do k = 1, size(mno_parameters,2)
       correlation_atom_term = correlation_atom_term + &
       c(k)*correlation_subterm(r_12,r_i1,r_i2,mno_parameters(1,k),mno_parameters(2,k)&
         ,mno_parameters(3,k))
     end do
References correlation_range(), and correlation_subterm().
Referenced by correlation_function().
correlation_function()
real(dp) function component_functions::correlation_function (real(dp), dimension(:,:), intent(in) atom_coords, real(dp), dimension(6), intent(in) electron_coords, integer, dimension(:,:), intent(in) mno_parameters, real(dp), dimension(:), intent(in) c, real(dp), intent(in) b, real(dp), intent(in) d)
Jastrow correlation fuction Function F from Schmidt and Moskowitz 1990.
Parameters
[in] atom_coords Coordinates of atoms
[in] electron_coords Coordinates of electrons
[in] mno_parameters Jastrow interger parameters
[in] c Jastrow dofs
[in] b Inverse lengthscale of nuclear-electron interaction
[in] d Inverse lengthscale of electron-electron interaction
Definition at line 145 of file component_functions.f90.
     real(dp) :: correlation_function
     real(dp), dimension(:,:), intent(in) :: atom_coords
     real(dp), dimension(6), intent(in) :: electron_coords
     integer, dimension(:,:), intent(in) :: mno_parameters
     real(dp),dimension(:), intent(in) :: c
     real(dp), intent(in) :: b
     real(dp), intent(in) :: d
     integer :: i ! Loop variable
     correlation_function = 0.0_dp
     do i = 1, size(atom_coords,2) ! sum over atoms
       correlation_function = correlation_function +&
        correlation_atom_term(atom_coords(:,i),electron_coords,mno_parameters,c,b,d)
     end do
     ! Compute exponential
     correlation_function = exp(correlation_function)
References correlation_atom_term().
Referenced by basis_functions::wave_function_2_electrons().
correlation_range()
real(dp) function component_functions::correlation_range (real(dp), intent(in) r, real(dp), intent(in) d)
Functions that construct the Jastrow interaction function Notation here follows Schmidt and Moskowitz 1990, refered to as SM90.
Jastrow subfuction: correlation range $\bar{r}$ function in Schmidt and Moskowitz 1990
Parameters
[in] r distance
[in] d inverse length scale
Definition at line 65 of file component_functions.f90.
     implicit none
     real(dp) :: correlation_range
     real(dp), intent(in) :: r
     real(dp), intent(in) :: d
     correlation_range = d * r/(1+d*r)
Referenced by correlation_atom_term().
correlation_subterm()
real(dp) function component_functions::correlation_subterm (real(dp), intent(in) r_12, real(dp), intent(in) r_I1, real(dp), intent(in) r_I2, integer, intent(in) m, integer, intent(in) n, integer, intent(in) o)
Jastrow subfuction: basic subterm Subterm of the correlation function, one for each Jastrow dof per atom This is the term in the k sum in Schmidt and Moskowitz 1990.
Parameters
[in] r_12 Distance between electrons
[in] r_i1 Distance from atom to electron 1
[in] r_i2 Distance from atom to electron 2
[in] m Triple of integer parameters. This is a row of mno_parameters
[in] n Triple of integer parameters. This is a row of mno_parameters
[in] o Triple of integer parameters. This is a row of mno_parameters
Definition at line 79 of file component_functions.f90.
     implicit none
     real(dp) :: correlation_subterm
     real(dp), intent(in) :: r_12
     real(dp), intent(in) :: r_I1
     real(dp), intent(in) :: r_I2
     integer,intent(in) :: m, n, o
     real(dp) :: delta ! coefficient to match Schmidt and Moskowitz 1990
     ! Value of delta, following Schmidt and Moskowitz 1990
     if (m==n) then
       delta = 0.5_dp
     else
       delta = 1.0_dp
     end if
     correlation_subterm = delta * (r_i1**m*r_i2**n+r_i1**n*r_i2**m)*r_12**o
Referenced by correlation_atom_term().