PX 915 Project Title/Name Here: draft_basis Module Reference
draft_basis Module Reference
Data Types
interface wave_function_interface
Functions/Subroutines
subroutine initialise_basis (n_electrons_in, n_basis_functions_per_atom_in, n_atoms_in, atom_coords_in)
subroutine deinitialise_basis
real(dp) function wave_function_slater_1s (position, dof_coefficients)
real(dp) function reduced_hamiltonian_slater_1s (position, dof_coefficients)
real(dp) function wave_function_sto3g (position, dof_coefficients)
real(dp) function reduced_hamiltonian_sto3g (position, dof_coefficients)
real(dp) function centered_gaussian (position, alpha)
real(dp) function centered_gaussian_laplacian (position, alpha)
real(dp) function centered_slater_1s (position, zeta)
real(dp) function centered_slater_1s_laplacian (position, zeta)
Variables
integer, protected number_dofs
real(dp), dimension(:,:), allocatable, protected dof_bounds
procedure(wave_function_interface), pointer wave_function => null()
procedure(wave_function_interface), pointer reduced_hamiltonian => null()
integer, private n_basis_functions_per_atom
integer, private n_electrons
integer, private n_atoms
integer, private n_dofs_per_atom
real(dp), dimension(:,:), allocatable, private atom_coords
logical, private initialised = .false.
Function/Subroutine Documentation
centered_gaussian()
real(dp) function draft_basis::centered_gaussian (real(dp), dimension(3), intent(in) position, real(dp), intent(in) alpha)
Definition at line 174 of file draft_basis.f90.
     implicit none
     real(dp), dimension(3),intent(in) :: position
     real(dp),intent(in) :: alpha
     real(dp) :: centered_gaussian
     ! Consider optimising this by precomputing abs x
     centered_gaussian = (2.0_dp * alpha /pi)**(0.75_dp)*exp(-alpha * dot_product(position,position))
References shared_constants::pi.
Referenced by centered_gaussian_laplacian(), and wave_function_sto3g().
centered_gaussian_laplacian()
real(dp) function draft_basis::centered_gaussian_laplacian (real(dp), dimension(3), intent(in) position, real(dp), intent(in) alpha)
Definition at line 183 of file draft_basis.f90.
     implicit none
     real(dp), dimension(3),intent(in) :: position
     real(dp),intent(in) :: alpha
     real(dp) :: centered_gaussian_laplacian
     ! Consider optimising this by precomputing abs x
     centered_gaussian_laplacian = &
     (-6.0_dp*alpha + 4.0_dp*alpha**2*dot_product(position,position))*centered_gaussian(position,alpha)
References centered_gaussian().
Referenced by reduced_hamiltonian_sto3g().
centered_slater_1s()
real(dp) function draft_basis::centered_slater_1s (real(dp), dimension(3), intent(in) position, real(dp), intent(in) zeta)
Definition at line 193 of file draft_basis.f90.
     implicit none
     real(dp), dimension(3),intent(in) :: position
     real(dp),intent(in) :: zeta
     real(dp) :: centered_slater_1s
     ! Consider optimising this by precomputing abs x
     centered_slater_1s = ( zeta**3 /pi)**(0.5_dp)*exp(-zeta * norm2(position))
References shared_constants::pi.
Referenced by centered_slater_1s_laplacian(), and wave_function_slater_1s().
centered_slater_1s_laplacian()
real(dp) function draft_basis::centered_slater_1s_laplacian (real(dp), dimension(3), intent(in) position, real(dp), intent(in) zeta)
Definition at line 202 of file draft_basis.f90.
     implicit none
     real(dp), dimension(3),intent(in) :: position
     real(dp),intent(in) :: zeta
     real(dp) :: centered_slater_1s_laplacian
     ! Consider optimising this by precomputing abs x
     centered_slater_1s_laplacian = &
     (-2.0_dp*zeta/norm2(position) + zeta**2)*centered_slater_1s(position,zeta)
References centered_slater_1s().
Referenced by reduced_hamiltonian_slater_1s().
deinitialise_basis()
subroutine draft_basis::deinitialise_basis
Definition at line 91 of file draft_basis.f90.
     implicit none
     if (initialised) deallocate(dof_bounds,atom_coords)
     initialised = .false.
References atom_coords, dof_bounds, and initialised.
Referenced by main().
initialise_basis()
subroutine draft_basis::initialise_basis (integer, intent(in) n_electrons_in, integer, intent(in) n_basis_functions_per_atom_in, integer, intent(in) n_atoms_in, real(dp), dimension(:,:), intent(in) atom_coords_in)
Definition at line 32 of file draft_basis.f90.
     implicit none
     integer, intent(in) :: n_basis_functions_per_atom_in, n_electrons_in, n_atoms_in
     real(dp), dimension(:,:), intent(in) :: atom_coords_in
     integer :: i
     integer :: n_dofs_per_basis_function
     ! Check and allocate the atom coordinates
     if (size(atom_coords_in,2) .ne. n_atoms_in ) then
       print*,"Error, wrong number of atoms"
       stop
     end if
     if (size(atom_coords_in,1) .ne. 3 ) then
       print*,"Error, wrong dimension of atom coordinates"
       stop
     end if
     allocate(atom_coords(3,size(atom_coords_in,2)))
     atom_coords = atom_coords_in
     ! Checks on inputs
     if (n_basis_functions_per_atom_in <= 0) then
       print*,"Error, number of basis functions per atom must be positive"
       stop
     end if
     n_basis_functions_per_atom = n_basis_functions_per_atom_in
     if (n_electrons_in .ne. 1) then
       print*,"Error, number of electrons must be 1" ! Change this later
       stop
     end if
     n_electrons = n_electrons_in
     if (n_atoms_in <= 0) then
       print*,"Error, number of basis functions per atom must be positive"
       stop
     end if
     n_atoms = n_atoms_in
     ! Hard coded number of dofs per basis function. This may change for a different choice
     n_dofs_per_basis_function = 2
     number_dofs = n_dofs_per_basis_function* n_basis_functions_per_atom * n_atoms
     n_dofs_per_atom = n_dofs_per_basis_function* n_basis_functions_per_atom ! Assign for convience and speed later
     allocate(dof_bounds(number_dofs,2))
     ! Ordering here is for 2 dofs per basis function, first linear cooef then width coeff
     ! c_1, alpha_1,c_2, alpha_2,
     do i = 1,n_basis_functions_per_atom*n_atoms
         dof_bounds(2*i-1,:)=[-1.0_dp,1.0_dp] ! Linear coeffs -1 to 1
         dof_bounds(2*i,:)=[0.1_dp,1.0_dp]   ! width positive, up to 1. May change the lower bound here
     end do
     ! Hard code choice of basis functions for now
     wave_function => wave_function_slater_1s
     reduced_hamiltonian => reduced_hamiltonian_slater_1s
     ! Set initialised flag, which is tested in the routines
     initialised = .true.
References atom_coords, dof_bounds, initialised, n_atoms, n_basis_functions_per_atom, n_dofs_per_atom, n_electrons, number_dofs, reduced_hamiltonian, reduced_hamiltonian_slater_1s(), wave_function, and wave_function_slater_1s().
Referenced by main().
reduced_hamiltonian_slater_1s()
real(dp) function draft_basis::reduced_hamiltonian_slater_1s (real(dp), dimension(3), intent(in) position, real(dp), dimension(:), intent(in) dof_coefficients)
Definition at line 119 of file draft_basis.f90.
     implicit none
     real(dp), dimension(3), intent(in) :: position
     real(dp), dimension(:), intent(in) :: dof_coefficients
     real(dp) :: reduced_hamiltonian_slater_1s
     integer :: i,j
     if (initialised) then
       reduced_hamiltonian_slater_1s = 0.0_dp
       do j = 0, n_atoms-1
         do i= 1,n_basis_functions_per_atom
           reduced_hamiltonian_slater_1s = reduced_hamiltonian_slater_1s &
             -0.5_dp * dof_coefficients( 2*i-1 +j*n_dofs_per_atom)&
               &*centered_slater_1s_laplacian(position-atom_coords(:,j+1), &
                 dof_coefficients( 2*i +j*n_dofs_per_atom ) )
         end do
       end do
       reduced_hamiltonian_slater_1s = reduced_hamiltonian_slater_1s/wave_function_slater_1s(position,dof_coefficients)
       do j = 0, n_atoms-1
       reduced_hamiltonian_slater_1s = reduced_hamiltonian_slater_1s &
         -1.0_dp /norm2(position-atom_coords(:,j+1))
       end do
     else
       print *, "Error, basis not initialised"
       stop
     end if
References atom_coords, centered_slater_1s_laplacian(), initialised, n_atoms, n_basis_functions_per_atom, n_dofs_per_atom, and wave_function_slater_1s().
Referenced by initialise_basis().
reduced_hamiltonian_sto3g()
real(dp) function draft_basis::reduced_hamiltonian_sto3g (real(dp), dimension(3), intent(in) position, real(dp), dimension(:), intent(in) dof_coefficients)
Definition at line 160 of file draft_basis.f90.
     implicit none
     real(dp), dimension(3), intent(in) :: position
     real(dp), dimension(:), intent(in) :: dof_coefficients
     real(dp) :: reduced_hamiltonian_sto3g
     integer :: i
     reduced_hamiltonian_sto3g = 0.0_dp
     do i= 1,number_dofs/2
       reduced_hamiltonian_sto3g = reduced_hamiltonian_sto3g &
        -0.5_dp* dof_coefficients( 2*i-1 )*centered_gaussian_laplacian(position, dof_coefficients( 2*i+1 ) )
     end do
     reduced_hamiltonian_sto3g = reduced_hamiltonian_sto3g/wave_function_sto3g(position,dof_coefficients) -1.0_dp /norm2(position)
References centered_gaussian_laplacian(), number_dofs, and wave_function_sto3g().
wave_function_slater_1s()
real(dp) function draft_basis::wave_function_slater_1s (real(dp), dimension(3), intent(in) position, real(dp), dimension(:), intent(in) dof_coefficients)
Definition at line 97 of file draft_basis.f90.
     implicit none
     real(dp), dimension(3), intent(in) :: position
     real(dp), dimension(:), intent(in) :: dof_coefficients
     real(dp) :: wave_function_slater_1s
     integer :: i,j
     if (initialised) then
       wave_function_slater_1s = 0.0_dp
       do j = 0, n_atoms-1
         do i= 1,n_basis_functions_per_atom
           wave_function_slater_1s = wave_function_slater_1s + &
             dof_coefficients( 2*i-1 + j*n_dofs_per_atom )&
               &*centered_slater_1s(position-atom_coords(:,j+1), &
                 dof_coefficients( 2*i + j*n_dofs_per_atom  ) )
         end do
       end do
     else
       print *, "Error, basis not initialised"
       stop
     end if
References atom_coords, centered_slater_1s(), initialised, n_atoms, n_basis_functions_per_atom, and n_dofs_per_atom.
Referenced by initialise_basis(), and reduced_hamiltonian_slater_1s().
wave_function_sto3g()
real(dp) function draft_basis::wave_function_sto3g (real(dp), dimension(3), intent(in) position, real(dp), dimension(:), intent(in) dof_coefficients)
Definition at line 148 of file draft_basis.f90.
     implicit none
     real(dp), dimension(3), intent(in) :: position
     real(dp), dimension(:), intent(in) :: dof_coefficients
     real(dp) :: wave_function_sto3g
     integer :: i
     wave_function_sto3g = 0.0_dp
     do i= 1,number_dofs/2
       wave_function_sto3g = wave_function_sto3g + dof_coefficients( 2*i-1 )*centered_gaussian(position, dof_coefficients( 2*i+1 ) )
     end do
References centered_gaussian(), and number_dofs.
Referenced by reduced_hamiltonian_sto3g().
Variable Documentation
atom_coords
real(dp), dimension(:,:), allocatable, private draft_basis::atom_coords private
Definition at line 26 of file draft_basis.f90.
   real(dp), allocatable, private, dimension(:,:) :: atom_coords
Referenced by deinitialise_basis(), initialise_basis(), reduced_hamiltonian_slater_1s(), and wave_function_slater_1s().
dof_bounds
real(dp), dimension(:,:), allocatable, protected draft_basis::dof_bounds
Definition at line 7 of file draft_basis.f90.
   real(dp), allocatable, dimension(:,:), protected :: dof_bounds
Referenced by deinitialise_basis(), initialise_basis(), and main().
initialised
logical, private draft_basis::initialised = .false. private
Definition at line 27 of file draft_basis.f90.
   logical, private :: initialised = .false.
Referenced by deinitialise_basis(), initialise_basis(), reduced_hamiltonian_slater_1s(), and wave_function_slater_1s().
n_atoms
integer, private draft_basis::n_atoms private
Definition at line 25 of file draft_basis.f90.
Referenced by initialise_basis(), reduced_hamiltonian_slater_1s(), and wave_function_slater_1s().
n_basis_functions_per_atom
integer, private draft_basis::n_basis_functions_per_atom private
Definition at line 25 of file draft_basis.f90.
   integer, private ::  n_basis_functions_per_atom, n_electrons, n_atoms, n_dofs_per_atom
Referenced by initialise_basis(), reduced_hamiltonian_slater_1s(), and wave_function_slater_1s().
n_dofs_per_atom
integer, private draft_basis::n_dofs_per_atom private
Definition at line 25 of file draft_basis.f90.
Referenced by initialise_basis(), reduced_hamiltonian_slater_1s(), and wave_function_slater_1s().
n_electrons
integer, private draft_basis::n_electrons private
Definition at line 25 of file draft_basis.f90.
Referenced by initialise_basis().
number_dofs
integer, protected draft_basis::number_dofs
Definition at line 6 of file draft_basis.f90.
   integer, protected :: number_dofs
Referenced by initialise_basis(), reduced_hamiltonian_sto3g(), and wave_function_sto3g().
reduced_hamiltonian
procedure (wave_function_interface), pointer draft_basis::reduced_hamiltonian => null()
Definition at line 12 of file draft_basis.f90.
   procedure(wave_function_interface),pointer :: reduced_hamiltonian => null()
Referenced by initialise_basis().
wave_function
procedure (wave_function_interface), pointer draft_basis::wave_function => null()
Definition at line 11 of file draft_basis.f90.
   procedure(wave_function_interface),pointer :: wave_function => null()
Referenced by initialise_basis().