PX 915: Variational Quantum Monte Carlo - LATIN: stoch_grad Module Reference
stoch_grad Module Reference
Optimization modules.
Functions/Subroutines
subroutine stoch_grad_init (N, best_from_last_run_in, seed)
Initalises module variables and sets up starts points for the restarts of the gradient assent.
subroutine stoch_grad_exit ()
deallocates state variables
subroutine grad_accent (X_0, sequence_length, no_samples, gamma, out)
Performs the gradient assent for sequence length X_0 is the intial point to start the assent at sequence_length is how long the sequence to average over is No_samlples is the number of samples taken in the gradient estimator, gamma is parameter to tune for how much to move the next point long the estimated gradient out is the output and used to compute the sum on the go.
real(dp) function, dimension(x_shape(1), x_shape(2)) g_t (X, no_samples, X_shape)
Return an estimate for the gradient which is an average over no_samples.
real(dp) function, dimension(:,:), allocatable nearest_point (bounds, X)
Returns a new point back to the search space if it leaves.
Variables
integer n_restarts
real(dp), dimension(:,:,:), allocatable n_points
Detailed Description
Optimization modules.
Function/Subroutine Documentation
g_t()
real(dp) function, dimension(x_shape(1),x_shape(2)) stoch_grad::g_t (real(dp), dimension(:,:), intent(in) X, integer no_samples, integer, dimension(2), intent(in) X_shape)
Return an estimate for the gradient which is an average over no_samples.
Parameters
X initial input
no_samples how many samples you want to use from the gradient estimator
X_shape defines the shape of the output
Definition at line 116 of file stoch_grad.f90.
     implicit none
     INTEGER:: no_samples
     real(dp), dimension(:,:), intent(in) :: X
     integer, dimension(2), intent(in) :: X_shape
     real(dp), DIMENSION(X_shape(1),X_shape(2)) :: G_t
     INTEGER :: i
     g_t=x
     do i = 1,no_samples
         g_t = g_t + run_gradient_estimator(g_t,gaussian(size(x,1)),n_dof,best_from_last_run)
     end do
     g_t = g_t/no_samples
References gradient_estimator::run_gradient_estimator().
Referenced by grad_accent().
grad_accent()
subroutine stoch_grad::grad_accent (real(dp), dimension(:,:), intent(in) X_0, integer sequence_length, integer no_samples, real(dp) gamma, real(dp), dimension(:,:), intent(out) out)
Performs the gradient assent for sequence length X_0 is the intial point to start the assent at sequence_length is how long the sequence to average over is No_samlples is the number of samples taken in the gradient estimator, gamma is parameter to tune for how much to move the next point long the estimated gradient out is the output and used to compute the sum on the go.
as result is taken as average, computing on the go uses less memory
Definition at line 58 of file stoch_grad.f90.
    implicit none
    real(dp), dimension(:,:),intent(in) :: X_0
    real(dp), dimension(:,:), intent(out) :: out
    real(dp), dimension(:,:), allocatable :: X_t,X_t_prev
    real(dp) :: gamma
    INTEGER::i,sequence_length,no_samples
    ALLOCATE(x_t(size(x_0,1),size(x_0,2)))
    ALLOCATE(x_t_prev(size(x_0,1),size(x_0,2)))
    x_t_prev=x_0
    out = x_t_prev
    do i = 1,sequence_length
     x_t= nearest_point(dof_bounds,(x_t_prev + gamma*g_t(x_t_prev,no_samples,shape(x_t))))
     out = out + x_t
     x_t_prev = x_t
    end do
    out = out/real(sequence_length+1)
References basis_functions::dof_bounds, g_t(), nearest_point(), and shared_constants::pi.
Referenced by biased_optim::bi_op_step().
nearest_point()
real(dp) function, dimension(:,:), allocatable stoch_grad::nearest_point (real(dp), dimension(:,:), intent(in) bounds, real(dp), dimension(:,:), intent(in) X)
Returns a new point back to the search space if it leaves.
Parameters
X new suggested point
bounds the degree of freedom bounds defined on input
Definition at line 140 of file stoch_grad.f90.
     implicit none
     real(dp), dimension(:,:), intent(in) :: bounds
     real(dp), dimension(:,:),INTENT(IN):: X
     real(dp), dimension(:,:),ALLOCATABLE:: X_Out
     INTEGER :: i,j
     ALLOCATE(x_out(size(x,1),size(x,2)))
     do i = 1,size(x,1)
         do j = 1 ,size(x,2)
             if (x(i,j)<bounds(j,1)) then
                 x_out(i,j)=bounds(j,1)
             else if (x(i,j)>bounds(j,2)) then
                 x_out(i,j)=bounds(j,2)
             else
                 x_out(i,j) = x(i,j)
             end if
         end do
     end do
Referenced by grad_accent().
stoch_grad_exit()
subroutine stoch_grad::stoch_grad_exit
deallocates state variables
Definition at line 44 of file stoch_grad.f90.
     implicit none
     deALLOCATE(n_points)
References n_points.
Referenced by main().
stoch_grad_init()
subroutine stoch_grad::stoch_grad_init (integer, intent(in) N, real(dp), intent(in) best_from_last_run_in, integer, dimension(:), intent(in) seed)
Initalises module variables and sets up starts points for the restarts of the gradient assent.
Parameters
N sets number of restarts
best_from_last_run_in gives the best energy from the last set of points
seed random seed in
Definition at line 23 of file stoch_grad.f90.
     implicit none
     INTEGER,INTENT(IN) :: N
     real(dp), intent(in) :: best_from_last_run_in
     integer, dimension(:), INTENT(IN):: seed
     integer :: i
     n_dof = size(dof_bounds,1)
     n_restarts = n
     ALLOCATE(n_points(n_restarts,n_restarts,n_dof))
     best_from_last_run=best_from_last_run_in
     do i=1,n_restarts
         call latin_hypercube(n_points(i,:,:),dof_bounds, n_restarts ,seed(1))
     end do
References basis_functions::dof_bounds, param_search::latin_hypercube(), n_points, and n_restarts.
Referenced by biased_optim::bi_op_step().
Variable Documentation
n_points
real(dp), dimension(:,:,:), allocatable stoch_grad::n_points
Definition at line 13 of file stoch_grad.f90.
     real(dp), DIMENSION(:,:,:), ALLOCATABLE :: N_points
Referenced by biased_optim::bi_op_step(), stoch_grad_exit(), and stoch_grad_init().
n_restarts
integer stoch_grad::n_restarts
Definition at line 11 of file stoch_grad.f90.
Referenced by stoch_grad_init().