PX 915 Project Title/Name Here: ising.f90 File Reference
ising.f90 File Reference
Functions/Subroutines
program main
Function/Subroutine Documentation
main()
program main
Definition at line 26 of file ising.f90.
References sweetener::define_axis(), sweetener::initialize(), sweetener::magnetization(), sweetener::parse(), sweetener::simulate(), and write_netcdf::write_data().