PX 915 Project Title/Name Here: square Module Reference
square Module Reference
Functions/Subroutines
subroutine get_length ()
subroutine from_python (l_, a_)
subroutine area ()
subroutine print_area ()
Function/Subroutine Documentation
area()
subroutine square::area
Definition at line 31 of file commonblock.f90.
     REAL(8) :: l, a
     COMMON /data/ l, a
     a = l**2
     print*,"The area of the square is: ",a
Referenced by main(), and print_area().
from_python()
subroutine square::from_python (real(8) l_, real(8) a_)
Definition at line 18 of file commonblock.f90.
     ! python inputs here
     REAL(8) :: l_, a_
     ! Fortran variables here
     REAL(8) :: l, a
     COMMON /data/ l, a
     l = l_
     a = a_
Referenced by get_length().
get_length()
subroutine square::get_length
Definition at line 9 of file commonblock.f90.
     REAL(8) :: l_, a_
     READ(*,*) l_, a_
     CALL from_python(l_, a_)
References from_python().
Referenced by main().
print_area()
subroutine square::print_area
Definition at line 43 of file commonblock.f90.
     CALL area()
References area().