PX 915 Project Title/Name Here: command_line Module Reference
command_line Module Reference
Functions to parse command line arguments.
Data Types
type cmd_arg
Type containing a key-value pair.
interface get_arg
Read arguments by name or number.
Functions/Subroutines
subroutine parse_args ()
Parse out command line args.
logical function get_arg_num_dbl (num, val, exists)
Read by number for double precision values.
logical function get_arg_name_dbl (name, val, exists)
Read by name for double precision values.
logical function get_arg_num_int (num, val, exists)
Read by number for long integer values.
logical function get_arg_name_int (name, val, exists)
Read by name for long integer values.
logical function get_arg_num_str (num, val, exists)
Read by number for string/character values.
logical function get_arg_name_str (name, val, exists)
Read by name for string values.
character(len=len) function get_arg_value (name, exists)
Lookup an argument by name and return the value as a string.
Variables
integer, parameter len = 30
Length of character value string.
type(cmd_arg), dimension(:), allocatable, private all_args
The argument list.
integer, private num_args = 0
The number of arguments.
Detailed Description
Functions to parse command line arguments.
Module to read command line arguments to a program We assume they are of the form name=value. There must NOT be spaces around the '=' sign! Value can be extracted as a string, a long-integer or a double-precision real. Argument names are limited to 20 chars, and values to 30 chars as read.
Note that the only functions you should call from outside are parse_args, get_arg and get_arg_value A complete example code is:
Author
H Ratcliffe
Function/Subroutine Documentation
get_arg_name_dbl()
logical function command_line::get_arg_name_dbl (character(len=*), intent(in) name, real(kind=real64), intent(out) val, logical, intent(out), optional exists)
Read by name for double precision values.
Parameters
name Argument name to look up
val Value to read into
exists Whether the name was found
Returns
True if the name is found and parsed, False otherwise
Definition at line 166 of file command_line.f90.
     LOGICAL :: get_arg_name_dbl
     CHARACTER(LEN=*), INTENT(IN) :: name
     REAL(KIND=real64), INTENT(OUT) :: val
     INTEGER :: i
     LOGICAL, INTENT(OUT), OPTIONAL :: exists
     LOGICAL :: found
     INTEGER :: ierr
     found = .false.
     ! Our cmd_arg type is already initialised to the sentinel
     DO i = 1, num_args
       IF(all_args(i)%name == trim(adjustl(name))) THEN
         found = .true.
         READ(all_args(i)%value, *, iostat=ierr) val
         EXIT
       END IF
     END DO
     IF(PRESENT(exists)) THEN
       exists = found
     END IF
     ! Return value is whether value is found and correctly parsed
     get_arg_name_dbl = (found .AND. (ierr == 0))
References all_args, and num_args.
get_arg_name_int()
logical function command_line::get_arg_name_int (character(len=*), intent(in) name, integer(kind=int32), intent(out) val, logical, intent(out), optional exists)
Read by name for long integer values.
Parameters
name Argument name to look up
val Value to read into
exists Whether the name was found
Returns
True if the name is found and parsed, False otherwise
Definition at line 232 of file command_line.f90.
     LOGICAL :: get_arg_name_int
     CHARACTER(LEN=*), INTENT(IN) :: name
     INTEGER(KIND=INT32), INTENT(OUT) :: val
     INTEGER :: i
     LOGICAL, INTENT(OUT), OPTIONAL :: exists
     LOGICAL :: found
     INTEGER :: ierr
     found = .false.
     ! Our cmd_arg type is already initialised to the sentinel
     DO i = 1, num_args
       IF(all_args(i)%name == trim(adjustl(name))) THEN
         found = .true.
         READ(all_args(i)%value, *, iostat=ierr) val
         EXIT
       END IF
     END DO
     IF(PRESENT(exists)) THEN
       exists = found
     END IF
     ! Return value is whether value is found and correctly parsed
     get_arg_name_int = (found .AND. (ierr == 0))
References all_args, and num_args.
get_arg_name_str()
logical function command_line::get_arg_name_str (character(len=*), intent(in) name, character(len=*), intent(out) val, logical, intent(out), optional exists)
Read by name for string values.
Parameters
name Argument name to look up
val Value to read into
exists Whether the name was found - this is already contained in the return value, but is given for consistency with the other members
Returns
True if the name is found and parsed, False otherwise
Definition at line 299 of file command_line.f90.
     LOGICAL :: get_arg_name_str
     CHARACTER(LEN=*), INTENT(IN) :: name
     CHARACTER(LEN=*), INTENT(OUT) :: val
     INTEGER :: i
     LOGICAL, INTENT(OUT), OPTIONAL :: exists
     LOGICAL :: found
     found = .false.
     ! Our cmd_arg type is already initialised to the sentinel
     DO i = 1, num_args
       IF(all_args(i)%name == trim(adjustl(name))) THEN
         found = .true.
         val = all_args(i)%value
         EXIT
       END IF
     END DO
     IF(PRESENT(exists)) THEN
       exists = found
     END IF
     ! Return value is whether value is found and correctly parsed
     get_arg_name_str = found
References all_args, and num_args.
get_arg_num_dbl()
logical function command_line::get_arg_num_dbl (integer, intent(in) num, real(kind=real64), intent(out) val, logical, intent(out), optional exists)
Read by number for double precision values.
Parameters
num Argument number to read
val Value to read into
exists Whether the name was found
Returns
True if the name is found and parsed, False otherwise
Definition at line 134 of file command_line.f90.
     LOGICAL :: get_arg_num_dbl
     INTEGER, INTENT(IN) :: num
     REAL(KIND=real64), INTENT(OUT) :: val
     LOGICAL, INTENT(OUT), OPTIONAL :: exists
     LOGICAL :: found
     INTEGER :: ierr
     found = .false.
     ! Check requested number is in range
     IF(num <= num_args .AND. num > 0) THEN
       ! READ it from string into value
       ! We don't need to specify the format in general
       READ(all_args(num)%value, *, iostat=ierr) val
       found = .true.
     END IF
     IF(PRESENT(exists)) THEN
       exists = found
     END IF
     ! Return value is whether value is found and correctly parsed
     get_arg_num_dbl = (found .AND. (ierr == 0))
References all_args, and num_args.
get_arg_num_int()
logical function command_line::get_arg_num_int (integer, intent(in) num, integer(kind=int32), intent(out) val, logical, intent(out), optional exists)
Read by number for long integer values.
Parameters
num Argument number to read
val Value to read into
exists Whether the name was found
Returns
True if the name is found and parsed, False otherwise
Definition at line 200 of file command_line.f90.
     LOGICAL :: get_arg_num_int
     INTEGER, INTENT(IN) :: num
     INTEGER(KIND=INT32), INTENT(OUT) :: val
     LOGICAL, INTENT(OUT), OPTIONAL :: exists
     LOGICAL :: found
     INTEGER :: ierr
     found = .false.
     ! Check requested number is in range
     IF(num <= num_args .AND. num > 0) THEN
       ! READ it from string into value
       ! We don't need to specify the format in general
       READ(all_args(num)%value, *, iostat=ierr) val
       found = .true.
     END IF
     IF(PRESENT(exists)) THEN
       exists = found
     END IF
     ! Return value is whether value is found and correctly parsed
     get_arg_num_int = (found .AND. (ierr == 0))
References all_args, and num_args.
get_arg_num_str()
logical function command_line::get_arg_num_str (integer, intent(in) num, character(len=*), intent(out) val, logical, intent(out), optional exists)
Read by number for string/character values.
Parameters
num Argument number to read
val Value to read into
exists Whether the name was found - this is already contained in the return value, but is given for consistency with the other members
Returns
True if the name is found and parsed, False otherwise
Definition at line 267 of file command_line.f90.
     LOGICAL :: get_arg_num_str
     INTEGER, INTENT(IN) :: num
     CHARACTER(LEN=*), INTENT(OUT) :: val
     LOGICAL, INTENT(OUT), OPTIONAL :: exists
     LOGICAL :: found
     found = .false.
     ! Check requested number is in range
     IF(num <= num_args .AND. num > 0) THEN
       ! READ it from string into value
       ! We don't need to specify the format in general
       val = all_args(num)%value
       found = .true.
     END IF
     IF(PRESENT(exists)) THEN
       exists = found
     END IF
     ! Return value is whether value is found and correctly parsed
     get_arg_num_str = found
References all_args, and num_args.
get_arg_value()
character(len=len) function command_line::get_arg_value (character(len=*), intent(in) name, logical, intent(out), optional exists)
Lookup an argument by name and return the value as a string.
Parameters
name Argument name to look up
exists Whether the name was found
Returns
The string value associated with the given name
Definition at line 336 of file command_line.f90.
     CHARACTER(LEN=len) :: get_arg_value
     CHARACTER(LEN=*), INTENT(IN) :: name
     LOGICAL, INTENT(OUT), OPTIONAL :: exists
     TYPE(cmd_arg) :: tmp
     INTEGER :: i
     LOGICAL :: found
     ! Initialise to the default value
     ! Use a temporary to get the default values
     ! This makes sure we match the expected sentinel
     get_arg_value = tmp%value
     found = .false.
     DO i = 1, num_args
       IF(all_args(i)%name .EQ. trim(adjustl(name))) THEN
         get_arg_value = all_args(i)%value
         found = .true.
         EXIT
       END IF
     END DO
     IF(PRESENT(exists)) THEN
       exists = found
     END IF
References all_args, and num_args.
parse_args()
subroutine command_line::parse_args
Parse out command line args.
Definition at line 84 of file command_line.f90.
     !Grab all command line args and store
     ! Strictly we can't be sure 50 chars is enough
     ! but for command-line args it's enough if we're sensible
     ! We wont overflow, but our strings may get truncated
     CHARACTER(LEN=51) :: arg
     INTEGER :: i, indx
     num_args = command_argument_count()
     IF(num_args > 0) THEN
       ! If this is not the first call, all_args may be already allocated
       ! Deallocate if needed, and allocate to correct size
       IF(ALLOCATED(all_args)) DEALLOCATE(all_args)
       ALLOCATE(all_args(num_args))
       ! Loop over all arguments
       DO i = 1, num_args
         CALL get_command_argument(i, arg)
         ! Location of the '=' sign
         ! If not found, return value is 0
         indx = index(arg, '=')
         IF(indx > 1) THEN
           ! All characters up to '=', not including it
           ! but with any leading spaces removed
           all_args(i)%name = adjustl(arg(1:indx-1))
           ! All characters after '='
           all_args(i)%value= adjustl(arg(indx+1:))
        ELSE
           all_args(i)%name = trim(adjustl(arg))
           ! Value already has a default value, so leave it alone
         END IF
       END DO
     ENDIF
References all_args, and num_args.
Referenced by sweetener::parse().
Variable Documentation
all_args
type(cmd_arg), dimension(:), allocatable, private command_line::all_args private
The argument list.
Definition at line 68 of file command_line.f90.
   TYPE(cmd_arg), DIMENSION(:), ALLOCATABLE :: all_args
Referenced by get_arg_name_dbl(), get_arg_name_int(), get_arg_name_str(), get_arg_num_dbl(), get_arg_num_int(), get_arg_num_str(), get_arg_value(), and parse_args().
len
integer, parameter command_line::len = 30
Length of character value string.
Definition at line 26 of file command_line.f90.
   INTEGER, PARAMETER :: len = 30
num_args
integer, private command_line::num_args = 0 private
The number of arguments.
Definition at line 70 of file command_line.f90.
   INTEGER :: num_args = 0
Referenced by get_arg_name_dbl(), get_arg_name_int(), get_arg_name_str(), get_arg_num_dbl(), get_arg_num_int(), get_arg_num_str(), get_arg_value(), and parse_args().