PX 915 Project Title/Name Here: sweetener Module Reference
sweetener Module Reference
Functions/Subroutines
subroutine parse (N, T, init, beta, J)
subroutine initialize (grid_in, grid_copy, N, init)
subroutine init_ferromagnet (grid_in, N)
subroutine init_random (grid_in, N)
subroutine init_alternating (grid_in, N)
real(real64) function magnetization (grid, N)
real(real64) function delta_e (grid, N, i, k, J)
subroutine simulate (grid, N, beta, J)
subroutine define_axis (axis, dim, val0)
Function/Subroutine Documentation
define_axis()
subroutine sweetener::define_axis (integer(int32), dimension(:), allocatable axis, integer(int32) dim, integer(int32) val0)
Definition at line 203 of file sweetener.f90.
     INTEGER(INT32) :: i, dim, val0
     INTEGER(INT32), DIMENSION(:), ALLOCATABLE :: axis
     ALLOCATE(axis(dim))
     axis = (/(i, i = val0, dim, 1)/)
Referenced by main().
delta_e()
real(real64) function sweetener::delta_e (integer(int32), dimension(1:n, 1:n), intent(in) grid, integer(int32), intent(in) N, integer(int32), intent(in) i, integer(int32), intent(in) k, real(real64) J)
Definition at line 167 of file sweetener.f90.
     INTEGER(INT32), INTENT(IN) :: N, i, k
     INTEGER(INT32), DIMENSION(1:N, 1:N), INTENT(IN) :: grid
     REAL(REAL64) :: J
     delta_e = j * real(grid(i, k) * (grid(i-1, k) + grid(i+1, k) + grid(i, k-1) &
     + grid(i, k+1)), kind=real64)
Referenced by simulate().
init_alternating()
subroutine sweetener::init_alternating (integer(int32), dimension(1:n, 1:n), intent(out) grid_in, integer(int32), intent(in) N)
Definition at line 139 of file sweetener.f90.
     INTEGER(INT32), INTENT(IN) :: N
     INTEGER(INT32) :: i, j
     INTEGER(INT32), DIMENSION(1:N, 1:N), INTENT(OUT) :: grid_in
     ! Setting the grid equal to 1 everywhere, then will alternate the interior
     grid_in = 1
     ! Alternating +/- 1's are intialized using the sum of the cell indices as
     ! the exponent for -1
     DO i = 2, n-1
       DO j = 2, n-1
         ! grid_in(i, j) = (-1)**(MOD(i+j, 2))
         IF(mod(i+j, 2)==0) grid_in(i,j) = -1
       END DO
     END DO
Referenced by initialize().
init_ferromagnet()
subroutine sweetener::init_ferromagnet (integer(int32), dimension(1:n, 1:n), intent(out) grid_in, integer(int32), intent(in) N)
Definition at line 106 of file sweetener.f90.
     INTEGER(INT32), INTENT(IN) :: N
     INTEGER(INT32), DIMENSION(1:N, 1:N), INTENT(OUT) :: grid_in
     grid_in = 1
Referenced by initialize().
init_random()
subroutine sweetener::init_random (integer(int32), dimension(1:n, 1:n), intent(out) grid_in, integer(int32), intent(in) N)
Definition at line 115 of file sweetener.f90.
     INTEGER(INT32), INTENT(IN) :: N
     INTEGER(INT32) :: i, j
     INTEGER(INT32), DIMENSION(1:N, 1:N), INTENT(OUT) :: grid_in
     ! Setting the grid equal to 1 everywhere, then will randomize the interior
     grid_in = 1
     ! For each non-boundary cell, a random number is drawn and cell is set to -1
     ! if it is < 0.5
     DO i = 2, n-1
       DO j = 2, n-1
         IF(random() < 0.5) grid_in(i, j) = -1
         ! Realized this else statement was unnecessary
         ! ELSE
         !   grid_in(i, j) = 1
         ! DO
       END DO
     END DO
References random_mod::random().
Referenced by initialize().
initialize()
subroutine sweetener::initialize (integer(int32), dimension(:, :), allocatable grid_in, integer(int32), dimension(:, :), allocatable grid_copy, integer(int32), intent(in) N, character(len=5), intent(in) init)
Definition at line 85 of file sweetener.f90.
     INTEGER(INT32), INTENT(IN) :: N
     INTEGER(INT32), DIMENSION(:, :), ALLOCATABLE :: grid_in, grid_copy
     CHARACTER(LEN=5), INTENT(IN) :: init
     ALLOCATE(grid_in(1:n, 1:n))
     ALLOCATE(grid_copy(1:n, 1:n))
     IF(init == "F" .OR. init == "f") THEN
       CALL init_ferromagnet(grid_in, n)
     ELSE IF(init == "R" .OR. init == "r") THEN
       CALL init_random(grid_in, n)
     ELSE IF(init == "A" .OR. init == "a") THEN
       CALL init_alternating(grid_in, n)
     END IF
     ! This makes a copy of the initial configuration for later
     grid_copy = grid_in
References init_alternating(), init_ferromagnet(), and init_random().
Referenced by main().
magnetization()
real(real64) function sweetener::magnetization (integer(int32), dimension(1:n, 1:n), intent(in) grid, integer(int32), intent(in) N)
Definition at line 159 of file sweetener.f90.
     INTEGER(INT32), INTENT(IN) :: N
     INTEGER(INT32), DIMENSION(1:N, 1:N), INTENT(IN) :: grid
     magnetization = sum(real(grid, kind=real64))/(real(size(grid), kind=real64))
Referenced by main().
parse()
subroutine sweetener::parse (integer(int32) N, integer(int32) T, character(len=5) init, real(real64) beta, real(real64) J)
Definition at line 22 of file sweetener.f90.
     INTEGER(INT32) :: N, T
     CHARACTER(LEN=5) :: init
     REAL(REAL64) :: beta, J
     LOGICAL :: success, exists
     ! We utilize the parse_args subroutine to collect and store all the
     ! command line arguments
     CALL parse_args
     ! get_arg is used on each argument individually to access them. If input is
     ! unreasonable, a default value is set for each of the parameters.
     success = get_arg("N", n, exists=exists)
     IF (.NOT. success) THEN
       n = 50
       print*,"N=50 default was used for grid size as there was no/incorrect &
       &command line input for N."
       print*,""
     END IF
     success = get_arg("T", t, exists=exists)
     IF (.NOT. success) THEN
       t = 1000000
       print*,"T=1000000 default was used for the number of timesteps as there &
       &was no/incorrect command line input for T."
       print*,""
     END IF
     ! The following checks to make sure that init is set to equal to one of
     ! {a, A, f, F, r, R} on the command line. If init is equal to anything else,
     ! a random initial grid is utilized.
     success = get_arg("init", init)
     IF(success)THEN
       IF (init == "A" .OR. init == "a" .OR. init == "F" .OR. init == "f" .OR. &
       init == "R" .OR. init == "r") THEN
         CONTINUE
       END IF
     ELSE
       init = "R"
       print*,"init=R default was used for the initial state as there was &
       &no/incorrect command line input for init."
       print*,""
     END IF
     success = get_arg("beta", beta)
     IF(.NOT. success) THEN
       beta = 2.0_real64
       print*,"beta=2.0 default was used for the temperature as there was&
       &no/incorrect command line input for beta."
       print*,""
     END IF
     success = get_arg("J", j)
     IF(.NOT. success) THEN
       j = 1.0_real64
       print*,"J=1.0 default was used for the interaction strength as there was &
       &no/incorrect command line input for J."
       print*,""
     END IF
References command_line::parse_args().
Referenced by main().
simulate()
subroutine sweetener::simulate (integer(int32), dimension(1:n, 1:n) grid, integer(int32) N, real(real64) beta, real(real64) J)
Definition at line 178 of file sweetener.f90.
     INTEGER(INT32) :: N
     INTEGER(INT32), DIMENSION(1:N, 1:N) :: grid
     INTEGER(INT32) :: rand_cell_i, rand_cell_j
     REAL(REAL64) :: beta, J, deltaE, P
     ! Add 2 to each index as we don't want to select cells from the boundary
     rand_cell_i = int(random()*(n-2), kind=int32) + 2
     rand_cell_j = int(random()*(n-2), kind=int32) + 2
     ! We obtain the change in energy of the selected cell's spin were flipped
     ! and flip the spin as given by the Ising Spin Model algorithm
     deltae = delta_e(grid, n, rand_cell_i, rand_cell_j, j)
     IF (deltae < 0) THEN
       grid(rand_cell_i, rand_cell_j) = -grid(rand_cell_i, rand_cell_j)
     ELSE IF (deltae > 0) THEN
       p = exp(-beta*deltae)
       IF(p > random()) THEN
         grid(rand_cell_i, rand_cell_j) = -grid(rand_cell_i, rand_cell_j)
       END IF
     END IF
References delta_e().
Referenced by main().